### PR TITLE
sound applet: player icon should not take priority over mute icon

### PR DESCRIPTION
**Pull request by benmccann**
closes https://github.com/linuxmint/cinnamon/issues/12393

### CODE REVIEW

**Review by claudiux — APPROVED** [review]

**Comment by leigh123linux** [comment]
@claudiux  Why are you merging commits without discussing them with the team first!!

**Comment by claudiux** [comment]
@leigh123linux I've tested these commits and they work well. It seems to me that the team had other problems to solve.

**Comment by JosephMcc** [comment]
@claudiux but you don't even know if this was a change that was wanted without any discussion. That's the point. Maybe it was and this is the right solution. But typically that decision is something that is cleared first.

**Comment by claudiux** [comment]
@JosephMcc When a PR solves a problem that has not been closed (cause: unplanned), it seems to me that this PR should be accepted.

**Pull request merged**
