### PR TITLE
fix users and groups falsely claiming that dots are allowed in usernames

### PR DESCRIPTION
**Pull request by Joshiy13**
fix users and groups falsely claiming that dots are allowed in usernames

### CODE REVIEW

**Comment by Joshiy13** [comment]
https://github.com/linuxmint/cinnamon/issues/12478

**Comment by fredcw** [comment]
The line you need to edit is [this one](https://github.com/linuxmint/cinnamon/blob/5b05d68226cd6c1b58709bc299e6946a83d9540a/files/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py#L376).

You then need to run `makepot` in the root directory to regenerate `Cinnamon.pot`. Actually, given that the only thing that will change in the `Cinnamon.pot` file when regenerated is the line you've already edited, you can probably get away with editing the .pot manually as you already have. Just make sure the string matches the one you change in `cinnamon-settings-users.py`

**Comment by Joshiy13** [comment]
Done

**Comment by Joshiy13** [comment]
Fixes https://github.com/linuxmint/cinnamon/issues/12478

**Comment by clefebvre** [comment]
.pot and /po shouldn't be modified.

To properly fix this we need to forbid . chars in the regex.

The label itself isn't actually necessary since the entry/button give feedback on invalid characters as they are being typed.

Fixed on master with https://github.com/linuxmint/cinnamon/commit/02480c68f20e3ce5f5deedae7976c23fb8643304

**Pull request closed without merging**
