### PR TITLE
Convert the force quit dialog to a cinnamon dialog

### PR DESCRIPTION
**Pull request by JosephMcc**

### CODE REVIEW

**Comment by anaximeno** [comment]
Hello @JosephMcc, does this PR fix the issue below as well?

Untitled
*fig - force quit dialog*

That text in the list view was not getting the proper text theme according to the dark theme (which should be white I suppose), also I'm not sure if the translation is implemented for that (if it is possible).

**Comment by JosephMcc** [comment]
Yes. It would no longer be a GTK dialog so that but would no longer be relevant.

**Comment by clefebvre** [comment]
> Hello @JosephMcc, does this PR fix the issue below as well?
> 
> Untitled _pic. - force quit dialog_
> 
> That text in the list view was not getting the proper text theme according to the dark theme (which should be white I suppose), also I'm not sure if the translation is implemented for that (if it is possible).

No, that's a different dialog. That's one of the session quit dialog.

**Comment by Alstruit** [comment]
It appears that the force quit dialog does not read the keyboard inputs (Tab,Left/Right keys). This may cause an issue if the application hides the mouse cursor.

**Comment by JosephMcc** [comment]
An oversight on my part. Hope to PR a fix in the next day or two.

**Pull request merged**
