### PR TITLE
Updated pkexec support

### PR DESCRIPTION
**Pull request by dg1727**
See https://github.com/linuxmint/mintsources/issues/75

In this pull request, file `files/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py` is modified for the sake of the `mdm` GitHub project, not the Cinnamon GitHub project.

### CODE REVIEW

**Comment by City-busz** [comment]
Please don't use the /usr/lib/linuxmint/common/mint-which-launcher.py script, because it's available only on Linux Mint. pkexec should be used instead of gksu.

**Comment by dg1727** [comment]
Thanks for pointing out about `mint-which-launcher.py`.  I will look into it.  
>pkexec should be used instead of gksu.

That's exactly the point.  :-)  Due to your comment, I double-checked, and indeed my modified code doesn't use `gksu`.

**Comment by City-busz** [comment]
>> pkexec should be used instead of gksu.
>
> That's exactly the point. :-) Due to your comment, I double-checked, and indeed my modified code doesn't use gksu.

The [mint-which-launcher.py](https://github.com/linuxmint/mint-common/blob/master/usr/lib/linuxmint/common/mint-which-launcher.py) uses gksu. So you didn't replace gksu, just made it impossible to run cinnamon-settings-users on other distributions.

**Comment by leigh123linux** [comment]
I'm -1 for this PR to be merged if it uses mint-which-launcher.py

**Comment by City-busz** [comment]
Why do you need gksu and kdesudo as fallback? pkexec is not enough? pkexec is available on all modern distributions.

**Comment by dg1727** [comment]
>The mint-which-launcher.py uses gksu. So you didn't replace gksu

At the same time that I modified `usr/bin/cinnamon-settings-users` to call `mint-which-launcher.py`, I modified `mint-which-launcher.py` (https://github.com/linuxmint/mint-common/pull/22) to use `pkexec` if it's available, rather than `gksu`.  

>Why do you need gksu and kdesudo as fallback? pkexec is not enough? pkexec is available on all modern distributions.

I use `gksu` and `kdesudo` as fallback because that's what the existing `mint-which-launcher.py` did.  

Further comments from the development team are welcome.

**Comment by leigh123linux** [comment]
@City-busz 

There is noting wrong with offering a choice.

> Why do you need gksu and kdesudo as fallback? pkexec is not enough? pkexec is available on all modern distributions.

**Comment by dg1727** [comment]
Replaced by #6336.

**Pull request closed without merging**
