### PR TITLE
Notifications: Add support for a bottom position option

### LINKED ISSUE #4892: Moving Notification pop-up on Cinnamon desktop
Hello,
Greetings from Turkey.
As I know, users can change notifications pop-up position in MATE but we can't in Cinnamon.
It always shows at the top-right corner but I would like to see at right-bottom area, over on clock, sound applets for example. Many of users want to change the place too.
In previously versions of Cinnamon's, users can change this situation via to modify Cinnamon.css but in 17.2 we can't even modify.
If you give some permissions to modify Cinnamon.css it would be great for us.
If you add an option to user interface of Notification Settings can change it like in MATE, it would be greater than.

Thanks in advance.
Best Regards,
dirent

### PR DESCRIPTION
**Pull request by jaszhix**
Depends on: https://github.com/linuxmint/cinnamon-desktop/pull/100

Closes #4892

### CODE REVIEW

**Comment by Marcosdw** [comment]
Hello,

i agree totaly

-------
Sorry, i use a oneline translator French/English

**Comment by MegaV0lt** [comment]
When willit be released?

**Comment by jaszhix** [comment]
Its for CInnamon 3.8, so probably sometime next spring/summer.

**Comment by Marcosdw** [comment]
Is there an alternative before cinnamon 3.8?

**Comment by jaszhix** [comment]
Not that I know of. If you are feeling confident in editing code and are okay with possibly having to re-install Cinnamon, can try this:

Look at the PR, in `js/ui/messageTray.js`, change [this line](https://github.com/linuxmint/Cinnamon/pull/7111/files#diff-065d2df89b17629dfc9c8771310bd705R1477) to `true` and remove this [block of code](https://github.com/linuxmint/Cinnamon/pull/7111/files#diff-065d2df89b17629dfc9c8771310bd705R1478) (3 lines). That should get it working on Cinnamon with CJS 3.4+. Copy the file to `/usr/share/cinnamon/js/ui/messageTray.js`. Restart Cinnamon. If there's a point release and you upgrade, the change will be lost.

**Pull request merged**
