### PR TITLE
[2.8] alter mouse motion values to reflect whats in c-s-d

### PR DESCRIPTION
**Pull request by leigh123linux**
The defaults in cinnamon-settings-daemon are -1 for both these settings, also it make no sense to invert motion-threshold.

### CODE REVIEW

**Comment by dalcde** [comment]
I think it makes sense to invert motion threshold, since it is labelled "sensitivity". High sensitivity would correspond to low threshold

**Comment by leigh123linux** [comment]
Having it inverted makes it look out of place compared to the other sliders.

**Comment by dalcde** [comment]
How?

**Comment by dalcde** [comment]
ok I see. I think we should fix that by impoving our inverted implementation instead.

**Comment by leigh123linux** [comment]
I agree.

**Pull request closed without merging**
