### PR TITLE
Slideshow applet: Show current file name in popupmenu

### PR DESCRIPTION
**Pull request by feugy**
I've added an item in the popup menu to show the current file name.
This is quite useful when you have a big set of wallpaper, and you want to know which one is displayed.

It's updated when menu opens, so it stays up to date when:
- users change the wallpaper by hitting "Next"
- wallpaper is changed automatically

I don't know yet how to provide the translation for `Current background:`, advises are welcome!

image

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @feugy,

Translation is fine, it's taken care of by our framework.

Can you add the menuitem and the settings objects to the applet constructor? That way they're not rebuilt every time you click the applet.

**Comment by clefebvre** [comment]
Careful also, you introduced blank spaces on line 14.

**Comment by feugy** [comment]
Hello @clefebvre. Thanks for your patience!
I've addressed your comments. Unfortunately, CI broke on something, _I think_, unrelated to this change.

Happy to address it if you give me instructions.

**Comment by clefebvre** [comment]
Thanks :)

**Comment by feugy** [comment]
\o/ 

Thank you so much!

**Pull request merged**
