### PR TITLE
Add button to remove Xlets

### PR DESCRIPTION
**Pull request by HenryJW**
Added Remove button for Xlets (applets, desklets, etc.). Button is disabled if there are no instances.

remove button

remove button disabled

### CODE REVIEW

**Comment by anandrkris** [comment]
Should "Uninstall" button be available as well? (Available only in right-click Context menu at the moment)

**Comment by HenryJW** [comment]
I don't think users uninstall often enough to need an Uninstall button. But I could be wrong.

**Comment by anandrkris** [comment]
Hmm. Thinking if these actions  can perhaps come as an icon against each row. Would it look clumsy?
Eg: Display Uninstall icon where it is not Locked.

**Comment by HenryJW** [comment]
I too think it would look clumsy. Unless someone can come up with a really good design for it.

**Pull request merged**
