### PR TITLE
CodeFactor style fixes

### PR DESCRIPTION
**Pull request by mrmajik45**
Style/Maintainability autofixes by CodeFactor.

### CODE REVIEW

**Comment by clefebvre** [comment]
What's !!?

**Comment by mrmajik45** [comment]
This converts a value to a boolean and ensures a boolean type.

**Comment by mrmajik45** [comment]
This is my first PR, so... Hi, my name is Auron.

**Comment by Odyseus** [comment]
Hello, everybody.

I'm not an expert, but I think that both uses of the double **NOT** operand (**!!**) are not needed. I think that by simply doing as follows is enough:

```javascript
let horizontal_panel = this.panelPosition == PanelLoc.top || this.panelPosition == PanelLoc.bottom
```

And even *better* would be to use strict comparisons.

```javascript
let horizontal_panel = this.panelPosition === PanelLoc.top || this.panelPosition === PanelLoc.bottom
```

**Comment by mrmajik45** [comment]
Hey man, i'm just posting CodeFactor's autofixes. I didn't type it.

**Pull request merged**
