### PR TITLE
notifications applet: new icons

### PR DESCRIPTION
**Pull request by NikoKrause**
these icons are from elementary icon theme

### CODE REVIEW

**Comment by germanfr** [comment]
Hey @NikoKrause, I wonder if you could add the `success` class to the normal notification dot?

**Comment by NikoKrause** [comment]
I talked with @clefebvre about this and he didn't wanted to be annoyed by the notifications.

**Comment by NikoKrause** [comment]
@germanfr I think the critical icons are never used. At least I wasn't able to trigger those icons with `notify-send`.

**Comment by NikoKrause** [comment]
Elementary OS 5 does animate it's panel icons now:
Elementary panel animations

**Comment by germanfr** [comment]
Critical notifications stay on screen and never go to the tray that I know. I mainly said it because they all are very similar icons and so that it was easier to tell if there was a notification at first sight.

**Comment by NikoKrause** [comment]
The notification applet is invisible by default. So if you see a bell, you know there's a new notification.

**Comment by NikoKrause** [comment]
And it shows the number of notifications

**Comment by germanfr** [comment]
True, true. It was just an idea. It doesn't really matter.

**Comment by NikoKrause** [comment]
Yeah, I had the same idea with adding the success class.

**Pull request merged**
