### PR TITLE
Indented battery status in power applet. 

### PR DESCRIPTION
**Pull request by fahmed24**
More information about the feature request, here.
https://github.com/linuxmint/Cinnamon/issues/4939

### CODE REVIEW

**Comment by fahmed24** [comment]
Can you possibly provide some resources to help me modify the style? I am having some trouble finding adequate documentation for St.BoxLayout and St.Label. Thanks.

**Comment by lestcape** [comment]
Ok... I see the problem. Well see, first thing is that: Add an style is pretty easy, but normally the devs of an app not want to add many different styles for several actors, because then will be pretty hard make a theme. So, they evaluate the best way to add the style that minimize the number of actors with an style and allowing the possibility of apply several modification, but of course not for all possible decisions. They can miss some important ones, but is a decision of who are controlling the cinnamon style add one more. So, i will recommended you instead of make your own style, request what you want, then will be possible evaluate if is really necessary. Create a theme is an art so, your personal appreciation, not always is the best for all people and sometime could not be convenient add an style because there are other reason, also if the changed will look better, probably could not be apply.

General help:
http://developer.linuxmint.com/reference/

A direct reference to the style property:
http://developer.linuxmint.com/reference/git/st/StWidget.html#StWidget--style

Inline Styling example:
actor.style = "<Here an style>"; // This is in the css way:

http://www.w3schools.com/css/css3_intro.asp
http://www.w3schools.com/html/html_css.asp
http://www.w3schools.com/css/css_syntax.asp

Real example:
statusLabel.style = '<Here your style>';

But as you can see here:
https://github.com/fahmed24/Cinnamon/blob/ac02b205454535583db4a41d34745c3f0df1ea46/files/usr/share/cinnamon/applets/power%40cinnamon.org/applet.js#L117

You have an style class called: 'popup-inactive-menu-item'

let statusLabel = new St.Label({ text: "%s".format(status), style_class: 'popup-inactive-menu-item' });

popup-inactive-menu-item is apparently a general style, so, what probably is the best is create a more specific one and add this style to the current one:

statusLabel.add_style_class_name('the-new-name');

Then you can set your properties inside the css file of your theme, or if you want to modify the cinnamon default style here:

https://github.com/linuxmint/Cinnamon/blob/4f40fd2aa40daba6273b388d727d7bae44f7a874/data/theme/cinnamon.css

You will need to know how create an style class in the css.

Regards.

**Comment by fahmed24** [comment]
Thanks @lestcape. I appreciate the feedback.

**Comment by clefebvre** [comment]
Hi,

There are two issues with this:

- RTL languages aren't taken into consideration
- The style you're changing isn't specific to the power applet (it's used somewhere else in Cinnamon and it can be used also by 3rd party applets/desklets).

Instead of adding padding here, I would recommend reviewing the layout of the power applet, maybe using a box to make the icon center on the left and have the two lines of text align with it or something.

Closing the PR in the meantime.

**Pull request closed without merging**
