### PR TITLE
add xdg-portal conf

### PR DESCRIPTION
**Pull request by leigh123linux**

### CODE REVIEW

**Comment by mtwebster** [comment]
Can you add xdg-desktop-portal-gtk to debian/control Depends?

**Comment by leigh123linux** [comment]
> Can you add xdg-desktop-portal-gtk to debian/control Depends?

Done.

**Comment by Fantu** [comment]
Sorry, when I saw this PR I didn't noticed that x-cinnamon-portals.conf was added to cinnamon package, I added [on Debian 4 months ago](https://salsa.debian.org/cinnamon-team/cinnamon/-/commit/f87c64f8d35ba406eb11ad442989a0716f6620cf) in cinnamon-common instead as don't arch dependent and without need to stay on arch dep. package FWIK. I also saw it similar in -common of mate and gnome.
Is there a reason to have it in cinnamon instead cinnamon-common? In that case I would move it in Debian

**Comment by mtwebster** [comment]
We can move it to cinnamon-common if that's better.

**Comment by Fantu** [comment]
After https://github.com/linuxmint/cinnamon/issues/11857#issuecomment-1913783526 I decided to move it to Debian in cinnamon

**Pull request merged**
