### PR TITLE
Cinnamon Settings: Adding capability to open specific tab and choose sort type

### PR DESCRIPTION
**Pull request by claudiux**
Usage:
`/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py applets 1 2`
opens the Applets window of Cinnamon Settings directly on Download tab (tab 1) with list of applets sorted by date (sort type 2).

The _applets_ word can be replaced by _desklets_, _extensions_ or _themes_.

The first number corresponds to the tab to open (tab 0 by default); the second number corresponds to the type of sorting:

- 0: sorting by name;
- 1: sorting by popularity;
- 2: sorting by date;
- 3: installed first.

This PR was requested by @jaszhix in https://github.com/linuxmint/cinnamon-spices-applets/pull/2235#issuecomment-456601075.

These changes do not affect all other settings.

Best regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
Hi @clefebvre,

I took into account the remarks you made in your comment https://github.com/linuxmint/cinnamon-spices-applets/pull/2235#issuecomment-457752201.

I hope this code will suit you.

**Comment by claudiux** [comment]
I have completely rewritten my code. It is now much simpler and reduces complexity.

**Comment by clefebvre** [comment]
Thanks @claudiux, it works well.

Here's my review:

- It needs to work from /usr/bin/cinnamon-settings as well
- I would recommend to call the tabs as they appear in English.. for instance "download" rather than "more"
- If possible I would recommend to add information about this in cinnamon-settings' MAN page and it's --help section.

**Comment by claudiux** [comment]
Hi @clefebvre,

Thanks for your review.

- Now, it works as well with `/usr/bin/cinnamon-settings`.
- I added "download" (and also let "more" respecting the code in cs_MODULE.py file).
- I added the capability to open a specific tab in xlets settings; each tab is identified by a number (starting at 0), which seems to be enough for a developer to use it.
- TODO: Add information into MAN page and --help section.

Best regards.

**Comment by claudiux** [comment]
Hi @clefebvre,

Here is the manpage. I hope it will suit you. I also reduced the message sent by `cinnamon-settings --help`.

Best regards.

**Comment by claudiux** [comment]
I do not understand why the tests fail on CircleCI.

**Comment by jaszhix** [comment]
Yeah, CI isn't working at the moment, it's not related to this PR. All of my recent PRs are failing too.

**Comment by claudiux** [comment]
Thank you for this information, @jaszhix. That worried me.

**Comment by claudiux** [comment]
Is it possible to redo the CI tests, now?

**Comment by claudiux** [comment]
Hi @clefebvre,

Should I do make changes, or another PR?

**Comment by clefebvre** [comment]
Sorry for the lack of communication on this.

**Pull request merged**
