### PR TITLE
Adapt Cinnamon to Mutter 3.36.9 rebase

### PR DESCRIPTION
**Pull request by clefebvre**
Depends on https://github.com/linuxmint/muffin/pull/601.

### CODE REVIEW

**Comment by Fantu** [comment]
@clefebvre @mtwebster thanks for your big works, very small advice: is good increase muffin build-deps/deps version to >=5.2 to avoid try to build/install with older version

**Comment by Fantu** [comment]
@mtwebster today after more tests of sounds I found that login sound don't work anymore (other sounds still works) and after debug I found that is return on startup_dalay in play function, removing it works correctly, is ok remove it or better fix is needed?

```
    play: function(sound) {
        **if (this.startup_delay)
            return;**
        if (this.enabled[sound] && this.file[sound] != "") {
            this.playSoundFile(0, this.file[sound]);
        }
    },
```

**Comment by mtwebster** [comment]
Yeah that was it, should be ok now, I should test more :)

**Comment by Fantu** [comment]
@mtwebster on latest tests login sounds now works correctly and with your latest commit also sounds settings are fully working, so csd-sounds remove result ok
during the various tests of these weeks I have seen big progress and almost all errors disappear from the logs, on latest tests I don't found any other issue or error in logs except things todo already wrote in first post of muffin PR, thanks for the very good job!
Thanks also to all other people who have contributed @clefebvre @JosephMcc

**Comment by Fantu** [comment]
@mtwebster in master there was merging of many PR and some with significant changes, I think that a rebase before continue to work and test is needed and I think is better do now instead do before other changes

**Comment by mtwebster** [comment]
Yeah I need to have a look at the new bases we'll be working from (both bullseye and whatever crazy name ubuntu 22.04 will have), and the newer mutter. I just need to move all this to a new vm first.

**Comment by Fantu** [comment]
@mtwebster thanks for all your works, rebase also on latest mutter seems another big changes, probably is better first rebase cinnamon changes and test them with the first big muffin rebase (was of 8 years if I remember good) instead have more difficult doing both at the same time

**Comment by Fantu** [comment]
@mtwebster I did a fast test for kb layout changes (https://launchpad.net/~fantonifabio/+archive/ubuntu/muffin-rebase - cinnamon rebase still missed) and don't show layout at start in both settings and applet:
actual-layout-missed

after adding 2 manually the applet still don't show on applet (even after logout-login), and if I disable and enable the kb applet show only the enabled one, I saw only one warning but I don't know if is related or not:
layout-switch-not-working

**Comment by Fantu** [comment]
@mtwebster big thanks for your big work

I rebased my PR on latest c-s-d version https://github.com/linuxmint/cinnamon-settings-daemon/pull/350 (is small but should still useful to save you a little time)
and also a commit to add here for increase c-s-d deps: https://github.com/Fantu/Cinnamon/commit/5f16c987cc5fd051b88195e2a694aa9021e4fb71

I also updated my PPA for any user that want do fast/easy tests
small note: is still based on latest mint based on Focal because I don't have enough time to rebuild all other packages (more details in PPA description and also an howto for use it)

**Comment by mtwebster** [comment]
Thanks

This is going to stay on the focal base - I made a quick attempt to rebase on bullseye's (Ubuntu 22.04's would have been too high to support debian also), but there would have been a huge impact on 3rd party spices, among other things... a lot of changes between 3.36 and 3.38 - there's a lot of work to do already, so I'm not really disappointed.

**Comment by Fantu** [comment]
about mutter version I also think is better stay to 3.36 and finish the work for it and release if possible for cinnamon 5.4 (this is a really big task...a full muffin rebase after over a decade; but is essential for the future of cinnamon) as continue to rebase also with cinnamon changes too many times can be a waste of time

about my previous comment I mean Focal about testing base and not another rebase to newer mutter (sorry if my english is not understandable enough)

**Comment by Fantu** [comment]
@mtwebster thanks for your work, now doing a very fast build it failed (https://launchpadlibrarian.net/583536736/buildlog_ubuntu-focal-amd64.cinnamon_5.3.0~git20220202_BUILDING.txt.gz):
src/st/meson.build:141: WARNING: Custom target input '['st-scroll-view-fade.glsl']' can't be converted to File object(s).
...
ninja: error: '../src/st/st-scroll-view-fade.glsl', needed by 'src/st/st-scroll-view-fade-generated.h', missing and no known rule to make it

seems related to https://github.com/linuxmint/cinnamon/commit/b885f7c0139948b87874ecd802e227577bfa55a6 that looking comment seems need require more work anyway, I have too low knowledge of meson and I'm a bit tired now and probably I'm wrong but i have noticed something that seems strange to me  a fast look to:

`data_to_c = find_program(meson.source_root() + '/src/data-to-c.pl')

glsl_sources = custom_target('scroll-view-fade-glsl',
  input: ['st-scroll-view-fade.glsl'],
  output: ['st-scroll-view-fade-generated.h'],
  capture: true,
  command: [data_to_c, '@INPUT@', 'st_scroll_view_fade_glsl']
)`

and "Usage: data-to-c.pl <filename> <variable>"

seems strange to me the @INPUT@ in command and/or input field above

**Comment by mtwebster** [comment]
Forgot to add a file. Fixed.

**Comment by Fantu** [comment]
@mtwebster thanks, now built correctly
about https://github.com/linuxmint/cinnamon/pull/10606 and https://github.com/linuxmint/cinnamon/pull/10596 I think is good to apply them for 5.2.8 (and in this branch) as make possible build correctly with meson>=0.61 (I already used them in debian unstable), are also a prerequisite for future building in ubuntu 22.04 that also have meson 0.61

for users that want fast/easy test it: https://launchpad.net/~fantonifabio/+archive/ubuntu/muffin-rebase/

**Comment by AxXxB** [comment]
@mtwebster Hello! I've created a PR #10671 with a big number of changes and Fantu said that maybe it could be useful if these changes will be merged here as well. The PR among other things contains a KbdLayoutController (similar to your KeyboardLayoutManager) that incapsulates XApp.KbdLayoutController and can be easy reimplemented to another layout API such as new muffin. What should I do? =)

**Comment by AxXxB** [comment]
Thanks a lot for your feedback!

**Comment by Secret-chest** [comment]
Thanks for your hard work. I would like to contribute when I have time, but I don't really know what should I do... like get a spare VM... also I do not know a lot about the GNOME ecosystem. However, are any configuration options removed?

**Pull request merged**
