### PR TITLE
[WIP] add swarm-symbolic.svg

### PR DESCRIPTION
**Pull request by NikoKrause**
This icon is from Entypo pictograms by Daniel Bruce — www.entypo.com, which is under CC BY-SA 4.0

The color was changed to #bebebe.

EDIT: 
I replaced the swarm.svg icon by Daniel Bruce with an icon by Dan Leech from https://github.com/danleech/simple-icons
The LICENSE.md file in Dan Leech repo says CC0 1.0 Universal.

### CODE REVIEW

**Comment by clefebvre** [comment]
If it's CC BY-SA 4.0 it needs attribution.

**Comment by NikoKrause** [comment]
@clefebvre 
I wasn't sure how doing that the right way.
In the FAQ on entypo.com it says:

> How do I give attribution?
A mention like “Entypo pictograms by Daniel Bruce — www.entypo.com” is considered acceptable attribution. You can place this in the footer of your website, on an about page or in the code if you don’t wanna give it to much attention.

I placed a comment in the code of the SVG file.
If it's not enough, please let me know, how I do it more properly.

**Comment by clefebvre** [comment]
It might impact AUTHORS, COPYING and debian/copyright.

If possible I'd recommend to find a public domain alternative or to make your own to keep licensing simple.

**Comment by NikoKrause** [comment]
I rebased the commit and edited the PR message to reflect this change. Please note also the commit message.

**Comment by NikoKrause** [comment]
@JosephMcc created cpu-symbolic.svg
So this icon here is not needed anymore.

**Pull request closed without merging**
