### PR TITLE
Improve dragging of items in GWL

### LINKED ISSUE #8639: Grouped Window List: juddering when moving items
```
 * Cinnamon version (cinnamon --version) 4.0.10
   - Please specify if you are using the daily builds PPA (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds): yes, but problem predates the alpha.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1.
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8.
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

When dragging items within the Grouped Window List applet, they judder from one position to another. That looks bad and makes the applet harder to use.

**Steps to reproduce**

Try dragging an item around a bit.
I'd attach a video but the Mint video tool remains broken (will hang the PC), so far as I know.

**Expected behaviour**

No juddering. Implementing some sort of threshold would do it, I imagine.

**Other information**

This is a cosmetic issue that many people will run into and it does not make the OS look good. Or so it seems to me.

### PR DESCRIPTION
**Pull request by ronyala**
* fix juddering when dragging items and improved animation (resolves #8639).
Personally I would recommend to change the animation to be like in `panel-launchers@cinnamon.org` (make selected item move _during_ dragging instead of making another empty space where you want to place it), but that's just taste.
* prevent pinned and unpinned items from getting mixed after dragging.
This seemed to me as the best option for the current state of GWL of usually causing ui issues when pinned and unpinned items are mixed, I am open to critisicm of this.

Edit: turned this into a Draft PR as I'm currently waiting for feedback and the code isn't perfect yet.

### CODE REVIEW

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=6330731&bid=20570295)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=6330731&bid=20570295)

**Comment by mtwebster** [comment]
This definitely improves dragging aesthetics. I'd been trying to address this [here](https://github.com/linuxmint/cinnamon/pull/9029), but got busy with other work. There were a couple of other issues with dnd as well, related to pinned apps - there's so much going on here it's hard to fix one thing without affecting 5 others.

I'm in agreement with using the panel launcher applet as a model for dnd behavior - it would probably also make dragging here a whole lot smoother without even trying. But this could be something for later (up to you).

**Comment by ronyala** [comment]
Actually, I aleardy made a panel-launchers style dragging a couple months ago while doing a previous PR, but I abandoned it.
This should be mostly a matter of finishing it, but it could take some time.

**Comment by ronyala** [comment]
The new changelog is in the commit.
Hopefully I didnt mess anything up, GWL seems pretty sensitive to changes.
Perhaps the same animation style should be used also in the `menu` applet and the panel edit mode? but that's for another day

**Comment by mtwebster** [comment]
Seems to work well.  Maybe you could add this:
```
diff --git a/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js b/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
index a5a047f37..3117093b2 100644
--- a/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
+++ b/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js
@@ -99,6 +99,9 @@ class AppGroup {
         });
         this.actor._delegate = this;
 
+        this.actor.set_easing_mode(Clutter.AnimationMode.EASE_IN_QUAD);
+        this.actor.set_easing_duration(100);
+
         this.progressOverlay = new St.Widget({
             name: 'progressOverlay',
             style_class: 'progress',
```
It's something I did with panel launchers to give a nice transition when dragging. I tried it here and it works just as well.


> GWL seems pretty sensitive to changes.

This is a huge understatement.

I was messing around with the appGroup:647 problem. the 'actor' is a Clutter.Rectangle (see js/ui/xdndHandler.js) and could be identified as a 'foreign' actor that way (xdndHandler engages with dnd between processes).

I also thought we could just add a name to that rectangle:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/xdndHandler.js#L20

by adding `name: "xdnd-proxy-actor"` or similar. Then you could check `actor.name` in the appGroup. I may do this anyhow because there are a number of other places this might be handy.

**Comment by ronyala** [comment]
Regarding the animation, I tried it and thought it was too wobbly to use (wobbles every time a window opens/closes). It's possible to add a workaround to use animation only during dragging, but I didn't want to add _more_ mess and workarounds to GWL.

About `xdndHandler.js`, adding a name does the trick - it turns out to be rather useful also in cleaning up checks a bit in GWL's `applet.js`.

By the way, is there any way to 'properly' debug cinnamon (breakpoints, inspect variables...)? I didn't find anything in the developer guide.

**Comment by mtwebster** [comment]
We can leave out the animation for now.

Regarding debugging, really the only way to break and resume is by connecting via ssh and attaching to the cinnamon process, though this won't help with js calls (besides seeing the underlying C functions in shared libraries). I think there's been improvement over the years in gnome-shell that might also be applicable to cinnamon but I've never investigated this.

**Comment by mtwebster** [comment]
This seems good - are you ok with it being merged?

**Comment by ronyala** [comment]
I have yet to see any problems with the changes and I don't think there is anything more to improve here.
Yes, I believe this PR is ready to be merged.

**Pull request merged**
