### PR TITLE
[WIP] Gwl ungrouped fixes

### PR DESCRIPTION
**Pull request by mtwebster**
Some fixes for ungrouped mode

See commit messages.  I'm uncertain about the last commit (DND zones).

### CODE REVIEW

**Comment by mtwebster** [comment]
This is for fixing the issue brought up here: https://github.com/linuxmint/mint19.3-beta/issues/23

Along with its related complications.

@smurphos @MenthaSuaveolens:

If you could try this out it would be great.. I'm sort of inventing behavior here for ungrouped mode, it was a bit undefined.  I'd appreciate any feedback.

**Comment by MenthaSuaveolens** [comment]
Fresh install of LM19.3. I can't reproduce the issue. 

I discovered another issue with the GIMP-icon when Gimp is installed by Flatpak. Starting GIMP creates another temp icon on the panel. It looks that the flatpak-app is considered as another app. The same happens with LibreOffice anyhow (writer-, calc- and impress-icons are created temporarily besides the LO-icon - which is ok, of course). 
FlatpakGimp

**Comment by smurphos** [comment]
@mtwebster - this fixes the presenting issue. The DND tweak makes sense to me and seems to work fine.

**Comment by smurphos** [comment]
@MenthaSuaveolens - there is an open issue for problems in app grouping with flatpak apps installed alongside repo version - https://github.com/linuxmint/cinnamon/issues/7974

**Comment by landon912** [comment]
Any updates or ETA on this? 

It would be a huge QOL improvement.

**Comment by GeorchW** [comment]
What's the issue with the PR? I can't look into the CI. I'd love to see this fixed.

**Comment by dhunter** [comment]
Obviously can't talk to the CircleCI test failure with lmde3, but for others who are using Cinnamon on the regular version of Mint 20, and are tired of having to re-add icons and/or restart Cinnamon multiple times a day, I went to /usr/share/cinnamon/applets/grouped-window-list@cinnamon.org, (made a copy, just in case) and manually added the bits from this pull request, and for more than a month now, it's worked without a hitch.  Has been a huge improvement, so would strongly suggest manually adding until whatever lmde3 test can be corrected, (again, after copying the unedited version, just in case).

**Comment by Ammako** [comment]
@dhunter if you need to make local edits, it's probably better to put the edited applet in ~/.local/share/cinnamon/applets rather than editing the files in usr.

**Pull request closed without merging**
