### PR TITLE
Fix RTL bugs in panel and applets

### PR DESCRIPTION
**Pull request by ronyala**
Fixes:
- dragging applets in panel edit mode
- dragging windows in ```grouped-window-list@cinnamon.org```
- dragging windows in ```window-list@cinnamon.org```
- dragging launchers in ```panel-launchers@cinnamon.org```

### CODE REVIEW

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js  1
- files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5929508&bid=19428466)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js  2
         

Clones added
============
- files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js  1
- files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5929508&bid=19428466)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- files/usr/share/cinnamon/applets/panel-launchers@cinnamon.org/applet.js  2
         

Clones added
============
- files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/applet.js  1
- files/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5929508&bid=19428466)

**Comment by mtwebster** [comment]
Man, this stuff *was* pretty broken.

Thanks

**Pull request merged**
