### PR TITLE
Fix CERTIFICATE_VERIFY_FAILED Issue

### PR DESCRIPTION
**Pull request by kelebek333**
Fix CERTIFICATE_VERIFY_FAILED Issue For Refresh Cache of Applets, Desklets, Extensions and Themes

https://github.com/linuxmint/cinnamon-spices-applets/issues/1569

### CODE REVIEW

**Comment by kelebek333** [comment]
This issue is related to the openssl version. The issue was solved with any fix, when I installed version 1.1.1 from PPA.

@clefebvre ; Could you update Openssl version to 1.1.1 for Linux Mint 18.x and Linux Mint 19.x series. Or could you import packages from following PPAs.

For Linux Mint 19.x series

https://launchpad.net/~mgrocock/+archive/ubuntu/openssl

For Linux Mint 18.x series

https://launchpad.net/~carsten-uppenbrink-net/+archive/ubuntu/postfix

**Comment by clefebvre** [comment]
Hi @kelebek333, no, this issue isn't related to openssl or cinnamon, it was a server issue on our side. Our SSL certs on spices expired and were renewed.

**Comment by kelebek333** [comment]
Hi @clefebvre,

I don't think so. The issue still continues. If I run modules with LC_ALL=C variable, the issue solving temporarily. For this reason you can not realize this problem. Because, the issue with your local settings does not occur. Could you try change your local settings with different languages to resolve them.

**Comment by wishx** [comment]
> Hi @kelebek333, no, this issue isn't related to openssl or cinnamon, it was a server issue on our side. Our SSL certs on spices expired and were renewed.

Your certificate wasn't expired for the past several months and wasn't supposed to expire until 2 days from now (per https://forums.linuxmint.com/viewtopic.php?f=90&t=259954&p=1581025#p1560965) unless I'm missing something and they had been expired for months and reporting improperly.

**Comment by clefebvre** [comment]
Thanks guys, sorry I was too quick to find the culprit. We did have a cert expiration, but you're right, the timing is wrong and if this is still happening, it's obviously still relevant :)

Reopening so :)

**Comment by kelebek333** [comment]
Hi @clefebvre ,

I think, this problem only occurs in language's without full ascii support. But the real reason of the problem is not cinnamon desktop. The real reason of the problem is related to openssl and fixed in its updated versions.

Three alternative things can be done about this issue.

1. You can this commit merge. But this not a real solution.
2. You can create a fix with utf-8 support.
3. Update openssl version. (This update can solve another potential issues related openssl) 

>  [ *) Windows command-line tool supports UTF-8 opt-in option for arguments
     and console input. Setting OPENSSL_WIN32_UTF8 environment variable
     (to any value) allows Windows user to access PKCS#12 file generated
     with Windows CryptoAPI and protected with non-ASCII password, as well
     as files generated under UTF-8 locale on Linux also protected with
     non-ASCII password.
     [Andy Polyakov]](https://www.openssl.org/news/cl111.txt)

**Comment by kelebek333** [comment]
Hi @clefebvre ,

I think, this issue only occurs in languages of without full ascii support. But the real reason of the issue is not cinnamon desktop or spices website. The real reason of the issue is related to openssl (and this fixed its updated versions).

Three alternative things can be done about this issue.

1. You can this commit merge. But this not a real solution.
2. You can create a fix with utf-8 support.
3. Update openssl version. (This update can solve another potential issues related openssl) 

>  [ *) Windows command-line tool supports UTF-8 opt-in option for arguments
     and console input. Setting OPENSSL_WIN32_UTF8 environment variable
     (to any value) allows Windows user to access PKCS#12 file generated
     with Windows CryptoAPI and protected with non-ASCII password, as well
     as files generated under UTF-8 locale on Linux also protected with
     non-ASCII password.
     [Andy Polyakov]](https://www.openssl.org/news/cl111.txt)

**Comment by clefebvre** [comment]
@kelebek333 what openssl version? Do you have a link to the bug report?

**Comment by kelebek333** [comment]
For examples, this; https://lists.ubuntu.com/archives/ubuntu-devel/2018-December/040567.html

For more; https://www.google.com/search?q=CERTIFICATE_VERIFY_FAILED+ubuntu+18.04&ie=utf-8&oe=utf-8

**Comment by kelebek333** [comment]
Hi @clefebvre,

Openssl's update also solves the problem of album cover missing issue on cinnamon sound applet.

With Openssl 1.1.0g

cinnamon-sound-spotify-1

With Openssl 1.1.1

cinnamon-sound-spotify-2

**Comment by clefebvre** [comment]
Nice, thanks @kelebek333, let's wait for the SRU update to fix this properly for us.

**Pull request closed without merging**
