### PR TITLE
[3.0] Signal manager: Timeouts and DBus

### PR DESCRIPTION
**Pull request by pixunil**
Adds following features to `SignalManager.SignalManager`:

- `SignalManager.addTimeout(name, interval, callback)`
 * `interval` is a number → milliseconds
 * `interval` is `null` → idle timeout
- `SignalManager.removeTimeout(name)`
- for `SignalManager.connect`, `obj` can also be a `Gio.DBusProxy`

I didn't convert all the old code, to have more security regarding regressions.

### CODE REVIEW

**Comment by dalcde** [comment]
I think this will conflict horribly with #4612, which simplifies a lot of the code in signalManager. Might be worth doing this on top of that commit instead.

**Comment by pixunil** [comment]
Okay, when #4612 gets merged, I'll rebase again.

**Comment by clefebvre** [comment]
That's not tested enough. I didn't review the code but found two regressions:

- The sound applet no longer reacts to the launch or death of an MPRIS media player.
- Window list thumbs seem to get stuck when hovering fast over many window list items and messing with Alt-Tab at the same time (probably a performance loss in signal manager).

I found a missing } which crashed Cinnamon in the other PR (Extension work) so I'm worried about the lack of testing here. It's a pity cause you're quite active on Cinnamon and these are really good ideas you're implementing. If you were more present on IRC and we could get to the point where I can trust your code blindly we'd do a lot more together.

It's still a really good PR but as it is I can't merge it in just yet. These two regressions need to be addressed and from a more general point of view, I'm getting really worried about potential regressions.

We've another day until feature-freeze. We can also postpone this to 3.0.

**Comment by dalcde** [comment]
I think we can separate out the api part and get that merged, but not actually use it for anything yet. That would be easier to audit and it would be rather helpful to 3rd party xlet developers.

**Comment by clefebvre** [comment]
Every time I add the sound applet to the panel, I get this:

(cinnamon:21219): Cjs-WARNING **: JS ERROR: TypeError: obj.connect is not a function
SignalManager.prototype._connectSignal@/usr/share/cinnamon/js/misc/signalManager.js:126
SignalManager.prototype.connect@/usr/share/cinnamon/js/misc/signalManager.js:116
MyApplet.prototype._init/<@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:910
_makeProxyWrapper/</<@resource:///org/gnome/gjs/modules/overrides/Gio.js:203

The sound applet successfully shows up, but I guess its signals are messed up. After that I start noticing the weird issue I mentioned earlier with the window list thumbs, I guess the signalManager is confused then.

I'm just looking at it from a black box tester point of view.

This WIP is promising but we're too close to 2.8 so I'm postponing it to 3.0.

**Pull request closed without merging**
