### PR TITLE
notifications: add button in applet settings, to open system settings

### LINKED ISSUE #9098: Feature request: in some fashion, combine the two lots of notification settings
```
 * Cinnamon version (cinnamon --version) 4.4.8
   - Please specify if you are using the daily builds PPA: no
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

Say you want to change a setting for notifications. Is the setting you want (let's say it is 'ignore transient notifications) in the configuration menu of the notification applet? Is the setting instead in System Settings -> Notifications? Are you even aware that there are two lots of settings?

Here's a screenshot of the two settings windows, when they are placed side by side:
image

If the two lots of settings can't or should not be unified - and one is for an applet, after all - then at least have a link, in the applet's settings, to the system settings, and - at least if the notifications applet is in use? - vice-versa.

### PR DESCRIPTION
**Pull request by claudiux**
Fixes #9098.

### CODE REVIEW

**Comment by mtwebster** [comment]
Can we get rid of the section header and just have the button labeled something like `Open notification settings`

**Comment by claudiux** [comment]
@mtwebster I used these messages because they are already translated. I'll commit the requested changes very soon.

**Comment by claudiux** [comment]
@mtwebster Should I squash my commits?

**Comment by mtwebster** [comment]
Yes please, looks good now

**Comment by claudiux** [comment]
@mtwebster Done.

**Pull request merged**
