### PR TITLE
Provide python3 and CLI interfaces to manage Cinnamon spice updates

### PR DESCRIPTION
**Pull request by clefebvre**
Make is possible for users and programs to manage Cinnamon spice updates.

- [x] Provide a python3 module
- [x] Provide a CLI utility

### CODE REVIEW

**Comment by NikoKrause** [comment]
@claudiux You might be interested in this PR.

**Comment by ItzSwirlz** [comment]
> @claudiux You might be interested in this PR.

Good point, I remember packaging some spices into Debian and lintian complained about some security thing for spices update.

**Comment by claudiux** [comment]
It's a good thing that Spices updates are supported directly by Cinnamon rather than an applet. This is what I should have done from the start. I am currently too preoccupied with the health crisis (family and friends) to be able to immerse myself in development. Thanks to the whole Cinnamon team for making this development.

**Comment by ItzSwirlz** [comment]
@claudiux Just reminding-once this P.R. is merged and 5.0x is out don't drop development until previous version support is dead ;)

I wish the best with well.. that.

**Pull request merged**
