### PR TITLE
Issue 7895: Changed label from "Fonts" to "Font Settings".

### PR DESCRIPTION
**Pull request by icarter09**
This is a PR for issue #7895. Changed the font label for the font that belongs to Cinnamon, the other belongs to Gnome.

### CODE REVIEW

**Comment by collinss** [comment]
@icarter09 Just fyi, those .desktop files are generated automatically with https://github.com/linuxmint/Cinnamon/blob/master/generate_cs_module_desktop_files.py. The name is pulled from the cs_fonts.py module in cinnamon-settings. Any changes you make to the desktop files will be overwritten the next time the script is run. I'm not sure what the best solution is though.

**Comment by icarter09** [comment]
@collinss Thanks for the heads up on that. I had a feeling that the .desktop files were being generated, but I wasn't sure how. Would changing the value of the name attribute in the Module class get picked up by the auto generator?

**Comment by collinss** [comment]
> Would changing the value of the name attribute in the Module class get picked up by the auto generator?

Yeah, it should. Adding 'settings' to the entry in cinnamon-settings might be a little bit redundant and inconsistent though.

**Comment by collinss** [comment]
Honestly I'm not sure what would be better. I'd almost be tempted to override the .desktop file for the other one instead. You could call it "Font Browser" or something. It would remove the ambiguity in the menu and would still work in Cinnamon Settings. Of course that would probably be a distribution-level change, but that might be better anyway. Idk though. This is probably one you want to defer to @clefebvre on.

**Comment by icarter09** [comment]
@clefebvre let me know what you think would be the best course of action for this ticket.

**Comment by clefebvre** [comment]
This should be requested upstream indeed, to GNOME.

MATE's font viewer describes itself as "MATE Font Viewer", ideally GNOME's should say "Font Viewer".

**Pull request closed without merging**
