### PR TITLE
network applet: Keep track of, but don't show, unmanaged networks

### PR DESCRIPTION
**Pull request by mtwebster**
Keep track of unmanaged networks (and listen to their
state changes) but don't let them show up in the network lists, and
don't have them count when it comes to section titles.

This follows up on a an initial effort to hide unmanaged networks but
which didn't take into account the possibility of those networks later
becoming manageable.  The revert commit, link to the original, as well
as some explanation is here: a1281a5d12584cbb6d0a183.

### CODE REVIEW

**Comment by maxyz** [comment]
If possible, could you rebase this change on top of #7536 ?

**Comment by clefebvre** [comment]
Following the move to libNM: 

Cjs-Message: 14:13:32.351: JS LOG: [LookingGlass/error] NetworkManager is not defined
Cjs-Message: 14:13:32.351: JS LOG: [LookingGlass/trace] 
<----------------
anonymous/CinnamonNetworkApplet.prototype._syncSectionTitle@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1882:1
anonymous/CinnamonNetworkApplet.prototype._deviceAdded@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1986:13
anonymous/CinnamonNetworkApplet.prototype._readDevices@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1928:13
anonymous/CinnamonNetworkApplet.prototype._clientGot@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:1814:13
---------------->

**Comment by mtwebster** [comment]
ok I'll have a look

**Comment by jaszhix** [comment]
Seems to work while using networkd as the renderer in the netplan config. 

Switching it to NetworkManager and running `sudo netplan apply` causes an error though, probably unrelated to this PR.

```
Cjs-Message: 14:14:51.646: JS LOG: [LookingGlass/error] a.connection is null
Cjs-Message: 14:14:51.646: JS LOG: [LookingGlass/trace] 
<----------------
anonymous/CinnamonNetworkApplet.prototype._syncActiveConnections@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:2047:17
anonymous/CinnamonNetworkApplet.prototype._updateIcon@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:2247:13
anonymous/CinnamonNetworkApplet.prototype._notifyActivated@/usr/share/cinnamon/applets/network@cinnamon.org/applet.js:2123:9
---------------->

(cinnamon:25574): St-CRITICAL **: 14:14:51.652: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Cinnamon warning: Log level 8: g_object_get: assertion 'G_IS_OBJECT (object)' failed
```

**Pull request merged**
