### PR TITLE
sound-applet: hide "Unknown Artist" on panel

### PR DESCRIPTION
**Pull request by archmunky**
When listening to streaming radio, metadata often includes Artist and Song in Title leaving the Artist field empty. This PR simply hides the " - Unknown Artist" text on the panel. This feature is switchable in settings and is set to false by default.

### CODE REVIEW

**Comment by clefebvre** [comment]
I agree to hide it when the info isn't there, but there's really no need for this to be configurable.

**Comment by archmunky** [comment]
Should I pull out the settings configuration code and push the update?

**Comment by clefebvre** [comment]
@archmunky yes, if you have time.

**Comment by clefebvre** [comment]
Thanks @archmunky

**Pull request merged**
