### PR TITLE
Implement optional "switch categories by clicking" option in menu applet 

### PR DESCRIPTION
**Pull request by Lurux**
This PR implements an optional "switch categories by clicking" option for the default menu applet in Cinnamon.

The option is now available as a toggle in the applet's settings, which have been rejigged a little bit to make the most important options more prominent.

This PR also adds an icon for the "all applications" category.

### CODE REVIEW

**Comment by Lurux** [comment]
Uhm also, I don't know how localization works here. Do I need to do anything on my end for translations to be added ?

**Comment by Lurux** [comment]
**Update:** added icon for "all applications" category, squashed the PR into two commits to clean things up.

It seems that most PRs here get answered in less time than this, do I need to do anything special for this to be reviewed ?

**Comment by icarter09** [comment]
There's nothing special that needs to be done. The PR will be reviewed in due time.

**Comment by Lurux** [comment]
I understand, thank you :slightly_smiling_face:

**Comment by mtwebster** [comment]
Hi, sorry for the delay - the category switching works well. But can you remove the All Applications icon? I don't think it really works here - I'd rather just leave it without an icon.

Thanks

**Comment by Lurux** [comment]
@mtwebster - I mean, I sure can do that; I just always found a bit awkward that the "all applications" category doesn't have a dedicated icon. Tbh I think the menu feels much better with it :sweat_smile:

Oh, I realize I also enabled menu animations by default to bring it in line with the rest of the applets. Should I revert that too ?

**Comment by clefebvre** [comment]
Yes please. Stick to 1 thing per PR to make it easier to merge/review/accept.

**Comment by Lurux** [comment]
Ok, I understand. I'll go ahead and change that, and merge it into a single commit to keep things clean.

Should I open a separate PR to add the icon and animation by default, or is this a straight "no" for both of these ?

**Comment by mtwebster** [comment]
Leave the animation off as well (mainly to keep from changing existing behavior on people - it's disabled to improve opening speed).

You can open a pr for the icon, though I'm personally against it (to me this is because it stands out compared to actual categories) but there can be more discussion I suppose.

**Comment by Lurux** [comment]
I did the changes as requested !

I can spin up a live usb to test the latest changes, though everything should be good :slightly_smiling_face:

**Comment by Lurux** [comment]
Yahoo ! :tada:

I have a question for next PR: should I stay on the same branch to implement the proposal PR to add an "all applications" icon, or should I create a new one ?

Anyways, expect to see me again around here ! :slightly_smiling_face:

**Pull request merged**
