### PR TITLE
Windows Settings: Add menu to button layout

### PR DESCRIPTION
**Pull request by leigh123linux**
https://github.com/linuxmint/cinnamon-control-center/issues/273

### CODE REVIEW

**Comment by hsbasu** [comment]
@leigh123linux Thanks a lot. After seeing your PR, I feel so idiotic of myself. Had I studied the code properly, I could have created a PR myself. It was this much easier. 👍🏾

**Comment by hsbasu** [comment]
When would this PR get merged? Really looking forward to it.

**Comment by JosephMcc** [comment]
I highly doubt that it will be. The plan is to move Cinnamon away from using Metacity theming, instead using the Gtk theming will handle the window decorations. Since really no themes support the menu button you'll end up with something that won't really work as expected.

**Comment by hsbasu** [comment]
@JosephMcc Should I close the PR?

**Comment by Secret-chest** [comment]
> The plan is to move Cinnamon away from using Metacity theming, instead using the Gtk theming will handle the window decorations.

Will the titlebars be huge? Please shrink them

**Pull request closed without merging**
