### PR TITLE
Settings and xlets performance and UI improvements

### PR DESCRIPTION
**Pull request by okaestne**
These commits do the following things:

###  Settings in general
* Fix quitting using Ctrl + C when started via terminal
* general code cleanup (unused variables, imports, missing white space reported by PyCharm..)

### xlets (applets, desklets, themes and extensions)
* let the tab for downloading xlets generate only generate when needed (clicked on). This improves the startup time notably.
* remove the ugly popup dialog (that appears if the spices cache is outdated) and replace it with a InfoBar
* general code cleanup (unused variables, imports, missing white space reported by PyCharm..)

I don't know what you think of the Infobar, I think it's looking muuch nicer. :)
Also please tell me if I should split these changes into separate PRs.

Btw: I also did some larger yet uncommited changes to the cs_themes, which generates the PictureChooserButtons for each theme element also on demand which more than halfs, almost third the startup time of the themes settings window which takes around 2100 ms (!) on my PC right now. The currently open PR #8804 boosts the performance a lot. I would like to create a PR based on that, once it's merged and if you don't mind.

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks @okaestne , I merged the 4 first commits. Can you rebase the last one?

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
- Added 3
           

Complexity decreasing per file
==============================
+ files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Cinnamon/Cinnamon/pullRequest?prid=4251372&bid=14522764)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
- Added 3
           

Complexity decreasing per file
==============================
+ files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cinnamon/Cinnamon/pullRequest?prid=4251372&bid=14522764)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
- Added 1
           

Complexity decreasing per file
==============================
+ files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cinnamon/Cinnamon/pullRequest?prid=4251372&bid=14522764)

**Comment by mtwebster** [comment]
I'm going to close this, I merged the final commit:
https://github.com/linuxmint/cinnamon/commit/9117c1d76c3cd1dd662256c09f2be915e228d641

Thanks!

**Pull request closed without merging**
