### PR TITLE
Port tinycss to tinycss2

### PR DESCRIPTION
**Pull request by marguerite**
tinycss’s last commit is in 2016, port it to tinycss2

### CODE REVIEW

**Comment by Fantu** [comment]
Hi, you need also change dep. in debian/control from python3-tinycss to python3-tinycss2

**Comment by Fantu** [comment]
I saw only now that tinycss2 is missed in both bionic and stretch, I suppose this PR will be merged only in a year or more when linux mint will use both new debian and ubuntu versions

**Comment by marguerite** [comment]
@Fantu I was just wondering why CI failed :-)

**Comment by mtwebster** [comment]
Hi, we ended up ripping out quite a bit of the existing tinycss code to fix some issues for 4.4.  Would you be willing to take another look to rebase? Otherwise I can take care of it eventually, it should be simpler now, if anything.

Thanks

**Comment by marguerite** [comment]
@mtwebster okay I will update the codes. Actually this is a continuous work because openSUSE never has tinycss but tinycss2

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 13
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=3998522&bid=13847016)

**Comment by marguerite** [comment]
@mtwebster 

Hi, I just finished the port work to cinnamon master branch, please review.

**Comment by marguerite** [comment]
The CI failed because debian has no tinycss2 packaged. but since we want tinycss2 for the Mint, a new CI VM needs to be set

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=3998522&bid=13847016)

**Comment by mtwebster** [comment]
Hi it works well the first time I try it - it adjusts the scroll bars correctly and saves it.  But when I go back in later to adjust more,  I get:

```
Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 669, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 173, in side_view_nav
    self.go_to_sidepage(cat, filtered_path, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 188, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 121, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 321, in sync_initial_switch_state
    editor = get_css_editor(self.selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 80, in get_css_editor
    css_instance = GtkCssEditor(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 105, in __init__
    for rs in stylesheet[0]:
TypeError: 'WhitespaceToken' object is not iterable

```

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=3998522&bid=13847016)

**Comment by marguerite** [comment]
@mtwebster try the latest rebased commit or just remove the '[0]'. I forgot to fully update the PR here.

**Comment by mtwebster** [comment]
Thanks!

**Pull request merged**
