### PR TITLE
Sound applet

### PR DESCRIPTION
**Pull request by pixunil**
Depends on linuxmint/cinnamon-settings-daemon#79

## New features
- application mixer to control the volume of each app #1874
- input device selector #1512
- if multiple player are launched, the player info "_Name_ - playing" is working as a submenu to select other players; no player gets "forgotten" #3385 #3882 
- middle click action can be configured to (un-) mute output or to toggle pause / play for the active player
- new players, got by DBus, are accessible via the player launcher

## Little enhancements
- can slide to 1%
- seek slider respects mouse scroll
- output device list should update whenever it is necessary #464 [lp:1285912](https://bugs.launchpad.net/linuxmint/+bug/1285912) [lp:1326590](https://bugs.launchpad.net/linuxmint/+bug/1326590)
- output device list is like the one in settings #2888 
- player launcher checks if the players still exist when software is uninstalled #3817
- input change is hearable
- respect `Rate` property #3750
- `soundManager.js`: handle gsettings update properly #3941

## Theming
- input and output sliders have got an icon left to them
- "Volume: n%" and "Microphone: n%" now are in a tooltip
- dropped class `sound-volume-menu-item`
- dropped SVGs `player-paused`, `-playing` and `-stopped`

sound-applet

### CODE REVIEW

**Comment by mtwebster** [comment]
Some feedback (Testing on Debian Jessie)

- No players appear by default (that's fine) - if I launch a player, it's recognized by the applet, also good.  But if I close the program, it won't let me re-launch it until I restart Cinnamon.
-- Launched Gnome Music, closed - result-> Launch Player now appears, but there is no expansion under it - it's empty.  Restart cinnamon, all is well.
-- Launch rhythmbox, close - result-> Still only showing gnome music, until I restart.

- If I have multiple players running, I switch between one to the other within the applet, I don't get track length info (and possibly other mpris info) - just the current time in the track.  (I could only test with a radio station, not sure what else might be missing)

- Should quit player be next to the player name at the top?  (just asking for discussion, not saying it should be so)

- This seems a bit confused:
image

-- I think it may be the fact that the slider doesn't align with the text above it - lose the icon and center the text?  or align the text with the slider?  Not sure - try some things?  Also, maybe there should be a separator between the main volume and the app volumes?  Seems a little crowded.

- Weird things happen to the main volume if you adjust the player volume - expected?

**Comment by pixunil** [comment]
1. _No players appear by default_ - fixed
2. _I don't get track length info_ - Can't reproduce atm
3. _Should quit player be next to the player name at the top?_ - Nice thought, but then Raise should be also there
4. _This seems a bit confused_ - Theme issue, with Mint-X and other 3rd party the submenus are colored something other. I think I talked a bit with @josephmcc on IRC
5. _Weird things happen_ - Can't reproduce atm

**Comment by JosephMcc** [comment]
3. If you do this you should probably add them with a style class of their own. Otherwise the buttons will probably be much larger than what you want in most cases. Not sure if I like the idea or not.

4. This is only partially a theme issue. I think a separator between the main volume slider and the "Applications..." label may not be a bad idea. Also kind of like the idea of centering the icon/label for the individiual applications in the submenu. Would have to see what it actually looks like.

**Comment by pixunil** [comment]
3) Yep, that's true, but as we aren't sure whether we implement it, we shouldn't discuss the details
4)
> I think a separator between the main volume slider and the "Applications..." label may not be a bad idea.

Personally, I thought this for a little moment in development but discarded it, because I thought that we have "Player | Output | (Input) | Settings" (| = separator) and I would dived the Output section with it. But if you think it has got better readability, I'll write this line of course.

> I think a separator between the main volume slider and the "Applications..." label may not be a bad idea.

A bit unconventional, right? (as everything is left-aligned).
The fact that the icon - label menuitem is not aligned like the icon - slider is true, I'm using a `St.BoxLayout` for the first and a `_allocate` hack (which I would like to dump) which respects the `_spacing` property for the slider.
I think that the easiest (and laziest) way for me to solve this is to wait for #3902.

**Comment by pixunil** [comment]
3) Yep, that's true, but as we aren't sure whether we implement it, we shouldn't discuss the details
4)
> I think a separator between the main volume slider and the "Applications..." label may not be a bad idea.

Personally, I thought this for a little moment in development but discarded it, because I thought that we have "Player | Output | (Input) | Settings" (| = separator) and I would dived the Output section with it. But if you think it has got better readability, I'll write this line of course.

> I think a separator between the main volume slider and the "Applications..." label may not be a bad idea.

A bit unconventional, right? (as everything is left-aligned).
The fact that the icon - label menuitem is not aligned like the icon - slider is true, I'm using a `St.BoxLayout` for the first and a `_allocate` hack (which I would like to dump) which respects the `_spacing` property for the slider.
I think that the easiest (and laziest) way for me to solve this is to wait for #3902.

**Comment by mtwebster** [comment]
Reminder - we can discuss anything we want, even if it's out of the scope of the current PR - maybe we want it *in* the scope :) - not saying we do, but we only know by discussion.

**Comment by anandrkris** [comment]
I remember suggesting this earlier, how about publishing this as a new applet in spices and seek feedback (assuming it works on 2.4)....

**Comment by pixunil** [comment]
@mtwebster, regarding 2), this shouldn't happen as the player section exists and can be modified. It is not added though, but this shouldn't have an effect an this. Do you have some more information for 5?

@anandrkris it works on 2.4, but you don't have got the audio feedback when changing sound, because I modified two Cinnamon js files and cinnamon-settings-daemon, which can't be installed over spices.

**Comment by mtwebster** [comment]
Sorry, got pulled away at work - 

I actually like this: https://trello-attachments.s3.amazonaws.com/5482ec374223fe02944e9598/279x360/b124c1e4f883830583edd14b71753b3e/sound_applet.png because the theme makes things not stand out...

I don't imagine our popup menu api would let you indent the section under "Applications..." ?

**Comment by mtwebster** [comment]
I think we're good here - the volume issue I was talking about, I think it's intentional, where if you raise an application's volume, it increases the main volume.

Can you squash?

**Comment by JosephMcc** [comment]
The changes to the applet broke compatibility with Pithos. No album art, song info, progress or anything is shown. It all worked before. The player can be tested by installing from the repos and just using a free account on Pandora.

**Comment by pixunil** [comment]
Sorry, I couldn't create an account for pandora, so I couldn't try to reproduce.
Do you have got something in your logs?

**Comment by mtwebster** [comment]
I did a little bit of debugging on it, it seems like the program doesn't set the 'rate' property, and everything falls apart from there.. defaulting to rate of 1 or rate of 1000 upon initializing the player interface allows the ui to finish loading, but we get no progress info - you can't seek pandora, but it should be able to show/update the current position.

I can make a dummy account for you

**Comment by pixunil** [comment]
okay, I blamed the desktopentry first, but this sounds more logical…

and according to http://www.pandora.com/restricted:

> We are deeply, deeply sorry to say that due to licensing constraints, we can no longer allow access to Pandora for listeners located outside of the U.S., Australia and New Zealand. We will continue to work diligently to realize the vision of a truly global Pandora, but for the time being we are required to restrict its use. We are very sad to have to do this, but there is no other alternative.

**Comment by JosephMcc** [comment]
@pixunil These are the errors I get in .xsession-errors whenever a song changes with pithos
```
(cinnamon:3348): Cjs-WARNING **: JS ERROR: Exception in callback for signal: PropertiesChanged: Error: value is out of range for Argument 'interval' (type guint32)
timeout_source@resource:///org/gnome/gjs/modules/mainloop.js:60
timeout_add@resource:///org/gnome/gjs/modules/mainloop.js:72
Player.prototype._runTimer@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:690
Player.prototype._setStatus@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:624
@/usr/share/cinnamon/applets/sound@cinnamon.org/applet.js:444
_emit@resource:///org/gnome/gjs/modules/signals.js:124
_convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:129
```

**Pull request merged**
