### PR TITLE
Use libnm >= 1.2, instead of deprecated libnm-glib

### PR DESCRIPTION
**Pull request by besser82**
This goes hand in hand with https://github.com/linuxmint/cinnamon-control-center/pull/173.

### CODE REVIEW

**Comment by mtwebster** [comment]
There's way more that needs fixed in the applet than just these imports. I'll come back to it when I get a chance.   The build-time changes here can be completely removed (in configure and makefile) - we only need the gir package in debian/control for runtime dependencies (and remove any other old network-related deps there also)

**Comment by Fantu** [comment]
@clefebvre you merged https://github.com/linuxmint/cinnamon-control-center/pull/173 but you missed to merge also this PR about the applet

**Comment by mtwebster** [comment]
This completely breaks the applet in its current form, as mentioned above.

**Comment by clefebvre** [comment]
Well the CCC PR seemed ready and it could be merged on its own.

**Comment by jbicha** [comment]
@clefebvre This issue still exists. Should this PR be reopened or should someone open an Issue?

**Comment by Fantu** [comment]
main job about is done in cinnamon-control-center https://github.com/linuxmint/cinnamon-control-center/commit/1966c6281cb7a8792a88edd40aa0b09f1c2fed0f
here is about the applet looking files in master is still present
mtwebster tell that broke the applet, these minimal changes in configure, makefile and import itself should not cause issue but api seems completly different: https://wiki.gnome.org/Projects/NetworkManager/Developers
In this case require major changes to the network applet code not present in this PR and not fast.

**Pull request closed without merging**
