### PR TITLE
Add a settings page for the nightlight

### PR DESCRIPTION
**Pull request by mtwebster**
Depends on:

https://github.com/linuxmint/cinnamon-settings-daemon/pull/402
https://github.com/linuxmint/cinnamon-desktop/pull/245

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, they look nice - my awesome icon is just a placeholder. Clem can take a look before we merge this stuff, he'll ultimately determine what we use.

Thanks

**Comment by mtwebster** [comment]
Merged - https://github.com/linuxmint/cinnamon/commit/8525e744694fec369d355023fa486fcbfb9f2dff

@haggen88 I added the Mint-X icon to Cinnamon (for fallback/non Mint installs) and the Mint-X theme.

I didn't do the Mint-Y theme because your icon's corner radii don't match what Mint-Y uses (or at least the existing icon I tried to modify there.

Can you have a look at that? Thanks!

**Comment by haggen88** [comment]
@mtwebster  I added a border, maybe that will correct it.
- [scalable_cs-nightlight__Mint Y.zip](https://github.com/user-attachments/files/17758417/scalable_cs-nightlight__Mint.Y.zip)

**Comment by haggen88** [comment]
@mtwebster  Now I noticed the difference in the borders, so I made this new icon by modifying an existing one.

[new scalable_cs-nightlight__Mint Y.zip](https://github.com/user-attachments/files/17896032/new.scalable_cs-nightlight__Mint.Y.zip)

PS. for mint 22.1 you guys plan to add power profiles ?, I have a couple of icons if you are interested.

**Pull request closed without merging**
