### PR TITLE
[WIP] Meson port

### PR DESCRIPTION
**Pull request by Salamandar**
To be fair, this one has not been tested at all. But the major part of the work is done, I think.

### CODE REVIEW

**Comment by Salamandar** [comment]
That'd be great if anyone could test/review it.

**Comment by Salamandar** [comment]
I rebased on Cinnamon 4.0.

**Comment by clefebvre** [comment]
Can you update debian/ as well?

**Comment by Salamandar** [comment]
OK.
I'll remove the autotools files too.

**Comment by Salamandar** [comment]
BTW, tests do not pass, but as I don't know JS at all, i leave it to you…

**Comment by clefebvre** [comment]
I think you need to call it manually. We're using debhelper 10 in LMDE.

**Comment by ItzSwirlz** [comment]
Should this be closed since we now have a properly working meson?

**Pull request closed without merging**
