### PR TITLE
Systray: Indicator alignment fix

### PR DESCRIPTION
**Pull request by brownsr**
Treats a minor systray bug.  Indicator icons in side panels are not centred, and this fixes that.  Only really becomes obvious with small icons, the fault is not noticeable with icons that are scaled to just fit in the panel. 

The same logic as is needed for BoxLayout in the panel is used here.  Blank labels are hidden to avoid spurious space in the systray, same reason as in the main applet.js code. 
 
**NB much of the conversation below has been superceded by a reduction in the scope of this PR**

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @brownsr can you rebase this one please?

**Comment by brownsr** [comment]
@clefebvre Rebased and given a quick test out.

**Comment by brownsr** [comment]
Some illustrative pictures
Master, defaults (but bigger panel)
master
Master, choosing a suitable icon size for the systray icons to look about right, scaling the symbolics to match.  Symbolics elsewhere go oversize. Note the offset systray icons
master 32px right scaled
With PR, defaults
pr
Same systray icon size and scaling for symbolics to match.  Same issue of symbolic scaling applying everywhere so symbolics in another part of the panel go oversize.  You can see the alignment issues resolved in systray.
pr 32px scaled

**Comment by clefebvre** [comment]
Master: 

image

this PR:

image

**Comment by brownsr** [comment]
Master, 16px, horizontal, Mint-Y


master 16px horizontal
PR, 16px, horizontal, Mint-Y
pr 16px horizontal

**Comment by brownsr** [comment]
You were clearly not convinced by the use of symbolic icon sizes in the systray, so I have removed all that.  Indicator icons will now come up controlled by applet-icon, which is the full colour CSS.  So essentially all this does now is fix the indicator alignment problem in vertical panels.

**Pull request merged**
