### PR TITLE
 massive notification reworks

### PR DESCRIPTION
**Pull request by itzexor**
I tried to mostly leave everything looking and functioning the same while removing all of the excess baggage and replacing the custom banner box to fix the ellipsizing behavior.

This definitely needs testing...there is probably quite a few bugs left.

### CODE REVIEW

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by mtwebster** [comment]
Functionally I like it and would like to merge for 4.6 - a couple of things I noticed:

- Test using the 'test notification' button in cinnamon-settings, the body text margin is good on the left, but on the right some text goes much closer to the edge of the box.
- There's no gap between the date/time and the heading in the applet - I think it's fine if the heading and body are spaced together, but the there should be slightly larger gap between the time and the heading.
- The icon could be a bit larger, and have some slight amount of margin between it and the text.  Maybe just larger.

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Clones removed
==============
+ js/ui/messageTray.js  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5164955&bid=16957034)

**Pull request merged**
