### PR TITLE
GWL: Set reasonable min width for panel item ...

### PR DESCRIPTION
**Pull request by fredcw**
... in case application icon is missing.

Fixes: https://github.com/linuxmint/cinnamon/issues/12307

### CODE REVIEW

**Comment by mtwebster** [comment]
If the application icon is missing there should be a placeholder/missing-image icon, not an empty space - I don't think this is a good way to address that issue.

**Comment by fredcw** [comment]
The problem is that app.create_icon_texture_for_window() and app.create_icon_texture() return an StIcon with no indication that the icon is missing and I don't see any obvious way to detect that. I have the same problem in Cinnamenu. I'll have another look later to see if I can find a way to do it.

**Comment by fredcw** [comment]
Ah, it seems that both `app.create_icon_texture_for_window()` and `app.create_icon_texture()` should return the icon `application-x-executable` where no other icon is found. But these don't seem to be working reliably.

**Comment by mtwebster** [comment]
I think since the example app/theme (breeze/alacarte) are defined and have a matching desktop file (so are not window-backed), we're [calling](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/appGroup.js#L274) `cinnamon_app_create_icon_texture ()`.

That gets the icon info from the GAppInfo (the desktop file representation) and never check if it's available before returning a useless StIcon.

This could be fixed easily in StIcon (checking the theme for the icon before trying to use it) but we'd lose the ability to have different context-dependent fallback icons (default app icon for gwl, missing image icon in other places, etc...).

It makes the most sense to check this as part of `cinnamon_app_create_icon_texture ()` maybe using `gtk_icon_theme_lookup_by_gicon ()`, but desktop files can also use an absolute path for their Icon entry - now you're checking if a file exists, which is racy...

I don't have a good answer yet lol I was just digging a bit.

**Comment by fredcw** [comment]
I think I have a solution. On line https://github.com/linuxmint/cinnamon/blob/master/src/cinnamon-app.c#L188 instead of `g_themed_icon_new`, use `g_themed_icon_new_from_names`.

I'm not sure how to do it in C but in JS I can use `Gio.ThemedIcon.new_from_names(['bob','application-x-executable'])` instead of `Gio.ThemedIcon.new('bob')` to get the 'application-x-executable' icon if `bob` doesn't exist.

**Comment by fredcw** [comment]
Actually, this only solves the problem for `cinnamon_app_create_icon_texture_for_window` but not for `cinnamon_app_create_icon_texture`.

In `cinnamon_app_create_icon_texture`, line 303:
```
icon = g_app_info_get_icon (G_APP_INFO (app->info));
```
also returns an invalid gicon.

**Comment by clefebvre** [comment]
Definitely a good issue to look into but the PR itself should be closed.

When the screen is too small to accommodate too many apps, the grouped window list icons get sliced/squashed:

image

It's not pretty but it means we see all apps.

Setting a minsize breaks that, it prevents the slicing/squashing so when there's no more space, we don't see the icon for newly added windows.

**Pull request closed without merging**
