### PR TITLE
sound@cinnamon.org - add keybinding to show applet menu

### PR DESCRIPTION
**Pull request by smurphos**
Adds end user configurable Super+S keybinding to display the sound applet menu.

### CODE REVIEW

**Comment by mtwebster** [comment]
This is used by the 'show desklets' keybinding', can we change the default? (if you go into keyboard shortcuts in cinnamon settings, and try to assign something it will complain if it's in use).

**Comment by mtwebster** [comment]
Also, are you missing the settings-schema.json change?
Please use 'Keyboard shortcuts' (plural) - this keeps all of these that you've added consistent and only a single string to translate.  It's still technically correct with one shortcut entry, since you can set two different keys if you want :)

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=5381906&bid=17646365)

**Comment by smurphos** [comment]
Thanks @mtwebster - I've gone for Shift+Super+S as the default.

For this one in the settings I've not added a separate section a the keybinding makes sense in the existing menu section.

**Pull request merged**
