### PR TITLE
Touch gestures

### PR DESCRIPTION
**Pull request by mtwebster**
To test in Mint 21 use: https://launchpad.net/~touchegg/+archive/ubuntu/stable/+files/touchegg_202304161121-stable-2.0.16~ubuntu22.04.1_amd64.deb. The current release package is broken.

Touchegg's client is currently killed by Cinnamon at startup. A pull request will be made to [disable it autostarting under Cinnamon](https://github.com/mtwebster/touchegg/tree/disable-client-cinnamon) once this is merged.

Requires https://github.com/linuxmint/muffin/commit/04e91f51325105bef5aee9049e245d89b4c11502 (already in muffin master).

### CODE REVIEW

**Comment by anaximeno** [comment]
There's a **two-finger scrolling** setting in the mouse and touchpad setting module:

Screenshot from 2023-05-27 00-52-48

I am not sure if this is relevant here, but it may be conflicting with a general gestures settings.

**Comment by Secret-chest** [comment]
Customisable?

**Comment by haggen88** [comment]
Hi @mtwebster, I have an icon proposal: [touchpad gestures_.svg.zip](https://github.com/linuxmint/cinnamon/files/11585639/touchpad.gestures_.svg.zip)

**Comment by mtwebster** [comment]
> Customisable?

Different actions can be assigned to the gestures, yes (including running custom commands).

@haggen88 thanks, updated.

**Comment by mtwebster** [comment]
@anaximeno Only 3 and 4-finger swipe will support gestures on touchpads. Touchscreens will allow it (which aren't affected by that setting).

**Pull request merged**
