### PR TITLE
applet.js: Fix access to destroyed Cinnamon.GenericContainer actor

### PR DESCRIPTION
**Pull request by AxXxB**
Under some (unknown) circumstances, I see these lines in .xsession-errors:
```
(cinnamon:2182): Cjs-CRITICAL **: 22:21:49.374: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800a8 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:331 (1fa19c54bba0 @ 174)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   7ffc5dedf580 b   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:49.376: st_widget_remove_style_pseudo_class: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:49.376: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800a8 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:332 (1fa19c54bba0 @ 200)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   7ffc5dedf580 b   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:49.377: st_widget_add_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:49.878: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:335 (1fa19c54bb50 @ 43)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:49.880: st_widget_has_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:50.380: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b3480160 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:331 (1fa19c54bba0 @ 174)
#1   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:50.382: st_widget_remove_style_pseudo_class: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:50.382: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b3480160 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:332 (1fa19c54bba0 @ 200)
#1   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:50.385: st_widget_add_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:50.886: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:335 (1fa19c54bb50 @ 43)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:50.888: st_widget_has_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:51.388: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b3480160 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:331 (1fa19c54bba0 @ 174)
#1   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:51.389: st_widget_remove_style_pseudo_class: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:51.389: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b3480160 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:332 (1fa19c54bba0 @ 200)
#1   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:51.390: st_widget_add_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:51.892: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800d0 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:335 (1fa19c54bb50 @ 43)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:51.893: st_widget_has_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:52.395: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800a8 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:331 (1fa19c54bba0 @ 174)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   7ffc5dedf580 b   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:52.398: st_widget_remove_style_pseudo_class: assertion 'ST_IS_WIDGET (actor)' failed

(cinnamon:2182): Cjs-CRITICAL **: 22:21:52.399: Object Cinnamon.GenericContainer (0x5580b48afb00), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5580b2bec140 ==
#0   5580b34800a8 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:332 (1fa19c54bba0 @ 200)
#1   5580b3480018 i   /usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function:340 (1fa19c54bb00 @ 24)
#2   7ffc5dedf580 b   /usr/share/cinnamon/js/misc/util.js:587 (2a594f8c3e20 @ 114)

(cinnamon:2182): St-CRITICAL **: 22:21:52.401: st_widget_add_style_class_name: assertion 'ST_IS_WIDGET (actor)' failed
```

It looks like some widget is trying to flash when it's actor destroyed (4 times calling a set of `remove_style_pseudo_class`, `add_style_class_name` and `has_style_class_name` with 1 second delay between sets). The commit fixes this behavour by adding `this._actorDestroyed` property to `AppMenuButton` class.

### CODE REVIEW

**Comment by clefebvre** [comment]
This looks like a workaround to me rather than a proper fix. I don't have time to look into it right now (we're pushing for the 5.2 release). I'll leave it open as WIP and look into it during the next cycle.

**Comment by AxXxB** [comment]
I'll try to explain to make it simpler for you when you'll look it later.

The reason of such a behaviour, when something is flashing after its actor is destroyed, is unknown - and, i think, is quite difficult to be figured out. But for me the code of `AppMenuButton` should not call destroyed actor anyway, i. e. it should never let it happen. Now this possibility exists because one can write something like:

```javascript
const button = new AppMenuButton(...);
...
button.getAttention();
...
button.destroy();
```

To handle this situation correctly (without a call to destroyed actor) we can either to make the actor alive while it's flashing or stop its flashing when it needs to be destroyed. I prefer second because this is what the user of `AppMenuButton` would expect.

So this change is a workaround in some degree, but it's a "good" workaround =)

**Comment by lestcape** [comment]
@AxXxB Maybe you want to have something like that to prevent a code execution after the actor was destroy as a cause of a timeout:

```js
_flashButton() {
    ...
    this._flashTimer = Mainloop.timeout_add(FLASH_INTERVAL, () => {
        ...
    });
    ...
 }

destroy() {
    ...
    if (this._flashTimer) {
        Mainloop.source_remove(this._flashTimer);
        this._flashTimer = null;
    }
    ...
}
```

**Comment by AxXxB** [comment]
@lestcape You're right, this way didn't come to my mind for some reason) Will rewrite.

**Comment by AxXxB** [comment]
Rewritten.

**Pull request merged**
