### PR TITLE
[Applet][Feature request] Allow multiple actions for Panel Launchers Applet icons

### PR DESCRIPTION
**Pull request by trolleyyy**
I've implemented feature request: (Allow multiple actions for Panel Launcher Applet icons) #3666
You may want to see how it works on screenshots available here: https://github.com/trolleyyy/MintPanelLauncher

### CODE REVIEW

**Comment by JosephMcc** [comment]
Cool, I haven't actually tried this yet but have a couple of comments. Please use consistent 4 spaces indentation to stay in line with what is already there. Also remove the "..." from the "More" item. We started removing those after adding back the expander arrows.

**Comment by trolleyyy** [comment]
Done, I prefer using "4 spaces length" tab indent in editors rather than space indent so I haven't seen this inconsistency before. Also dots from "More" item removed already.

**Comment by mtwebster** [comment]
Would it make sense to have this functionality in the window list applet also?

Works nice, thanks :)

**Comment by trolleyyy** [comment]
It would be nice to have this functionality in the window list applet too, but after fast look into window list applet code it seems, that it is really not intended to do it. Apparently in windows list applet we have only handle for window, not referenced desktop file. Maybe there are some way to do it, I'll think about it later.

**Pull request merged**
