### PR TITLE
[3.2] Add applet name to the applet context menu item that deletes the applet

### PR DESCRIPTION
**Pull request by brownsr**
fixes feature request #5214

### CODE REVIEW

**Comment by clefebvre** [comment]
It's not very elegant.

Remove applet "User Applet"
Remove applet "Sound"
Remove applet "Calendar"

Could we simplify it to "Remove %s" instead?

Remove "User Applet"
Remove "Sound"
Remove "Calendar"

**Comment by f2404** [comment]
I agree.

And maybe also add applet names to other menu items? Or add a kind of title on top of them.
I mean, it would be elegant to show
```
About...
Configure...
Remove "Power Manager"
```
all items should be in the same style.

**Comment by clefebvre** [comment]
You mean repeating the name of the applet in each item? that's a bit too much isn't it?

Maybe we could add a title on top of the context menu, with the name of the applet, and then leave the action items the way they were.

**Comment by f2404** [comment]
Yes, I realized repeating was too much, and suggested to add a title with applet name.

**Comment by JosephMcc** [comment]
Actually that whole "..." thing trailing the text could really go away as well.

**Comment by brownsr** [comment]
will resubmit this, need to clean my git repository up to move this out of my master

**Pull request closed without merging**
