### PR TITLE
[WIP] menu applet: use scrollbox for categories

### PR DESCRIPTION
**Pull request by NikoKrause**
resizing of the menu is not ideal and needs to be improved in the long
run

### CODE REVIEW

**Comment by clefebvre** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cinnamon/Cinnamon/pullRequest?prid=6373191&bid=20679298)

**Comment by mtwebster** [comment]
I'm not ignoring this, I'd like to get resizing working to go with it.

**Comment by NikoKrause** [comment]
Yes, I thought so. No hurry from my side

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/7fd1d5b67563a611c890f29e2408291cc3e2acc0

**Pull request closed without merging**
