### PR TITLE
Fix several bugs with applet dnd

### PR DESCRIPTION
**Pull request by collinss**

### CODE REVIEW

**Comment by 2017-05-1200-11-20** [comment]
index.json

**Comment by 2017-05-1200-11-20** [comment]
set by Nemo,
- NEMO_SCRIPT_SELECTED_URIS

**Comment by 2017-05-1200-11-20** [comment]
*.patch...

**Comment by leigh123linux** [comment]
@2017-05-1200-11-20  F* off!

**Pull request merged**
