### PR TITLE
calendar@cinnamon.org: patch for issue #9196

### PR DESCRIPTION
**Pull request by sidorsett**
Patch for the issue #9196

### CODE REVIEW

**Comment by mtwebster** [comment]
I don't think there's a need for an additional setting - If you prefer it a certain way on the panel why not use that same format in the popup?  This is the only thing that needs fixing I think.

**Comment by sidorsett** [comment]
Hello, Michael.

Thanks for sharing your considerations. From my side, it is an attempt to probe the ground and to learn how the open SW community works. This is my first code contribution ever, and I have some more ideas ;) Therefore, I really appreciate your response!

> I don't think there's a need for an additional setting - If you prefer it a certain way on the panel why not use that same format in the popup? This is the only thing that needs fixing I think.

Indeed, I and probably many others prefer to have them in different ways:
- Time only in the panel.
- Date in the popup.

**Rationale:** Date takes a lot of space in the panel, it doesn't change often, and you don't need to reference it often. Hence, it is fine to "hide" the date into the popup, where it can get as much space, as necessary. The time on the other hand takes the moderate amount of space on the panel; the time changes often; this is what you reference frequently and want to have visible without additional mouse clicks.

Time is what all versions of Windows have on the panel. The full date is in the popup.
"Windows" does not sound as a good authority? Well, this calendar applet itself has defaults of time for the panel and of date for the popup. Though, the applet gives you an option to configure label in the panel, but doesn't give you an option to set up format of the date in the popup. I am absolutely fine with the default setting for the panel (i.e. time). I rather don't need the configuration for the that (i.e. for the panel). But I also want to have the correct format of the date in the popup. And I am not alone. You can find people facing the similar issue for years. See [this](https://forums.linuxmint.com/viewtopic.php?t=244125) for example. Is this the right option for them to change the code? No!

It would be ideal to use the localization settings for the date in the popup. I don't know, how to do that. If you give me the hint, I can make the changes myself.

Cheers!

**Comment by mtwebster** [comment]
Ok fair enough - did a little more investigating on the history of this applet and my suggestion wouldn't have been well-received :)

We need to have the default (current) value continue to be translated thru CinnamonDesktop.WallClock.lctime_format().  That is the default string that gets translated (so it has to be exactly that).

So I would say add another switch specifically for the new field.  So we'd have two switches with two hidden custom fields (which I'm not crazy about but otherwise if someone wants just to change the panel label, they'd lose the date translation we currently perform).

Also, let's use these labels:

switch: Use a custom format for the panel
label: Panel format
tooltip: Set the custom format for the panel

and

switch: Use a custom date format for the calendar
label: Calendar date format
tooltip: Set a custom date format for the calendar

We'll see how that looks..

**Comment by sidorsett** [comment]
Hello, Michael.

Thanks for the feedback. Trying to understand how lctime_format() works, I encountered the issue #9042, which seems to fix the problem in Cinnamon 4.4.8. Hence, I am thinking that the fix proposed by me is not necessary. Though, I would like to play a bit with my older Cinnamon version, before recalling the pull request.

I'll be back.

Cheers!

**Pull request closed without merging**
