### PR TITLE
Replace the default Cinnamon theme

### PR DESCRIPTION
**Pull request by JosephMcc**
Replaces the very outdated default cinnamon theme with something more up-to-date. May still be a few issues here and there that more testing/using will turn up. A few things are also on the roadmap to update style wise. This will set the base for those to come next.

### CODE REVIEW

**Comment by Initu-Castilhos** [comment]
❤️

**Comment by Initu-Castilhos** [comment]
Will it be available for download so I can test it?

**Comment by JosephMcc** [comment]
@Initu-Castilhos No it can't be downloaded anywhere. It's part of Cinnamon and I'm not developing it as anything else at the moment.

A couple screenshots of the new dialog styling.
Screenshot from 2024-09-15 20-56-40

Screenshot from 2024-09-15 20-57-08

**Comment by JosephMcc** [comment]
Updated calendar applet styling

Screenshot from 2024-09-15 21-22-48

**Comment by Initu-Castilhos** [comment]
Thanks for the reply!

**Comment by Initu-Castilhos** [comment]
Will it have the gtk theme and icons too?

**Comment by JosephMcc** [comment]
@Initu-Castilhos No. Cinnamon doesn't include Gtk and icon themes by default. This is just the default cinnamon theme which gets used when you install Cinnamon in distros outside of Mint. Many of those distros don't have a curated Cinnamon version like Mint does.

**Comment by Initu-Castilhos** [comment]
Can you make the theme's cinnamon.css file available?

**Comment by JosephMcc** [comment]
@Initu-Castilhos In this case it wouldn't do much good. There are actual code changes in the branch to redesign some things. Without those the theme won't work the same. You need to actually build and use the branch.

**Comment by Initu-Castilhos** [comment]
> @Initu-Castilhos In this case it wouldn't do much good. There are actual code changes in the branch to redesign some things. Without those the theme won't work the same. You need to actually build and use the branch.

Ok!

**Comment by clefebvre** [comment]
In the source the theme is written in SASS. In the OS once installed you can see the CSS in /usr/share/cinnamon/theme.

**Pull request merged**
