### PR TITLE
[WIP] Bring back polkit authentication agent (and patch it...)

### PR DESCRIPTION
**Pull request by ItzSwirlz**
This was removed in 2.0.8 and left us to rely on policykit-1-gnome by 
other applications such as pkexec, which is unmaintained (last commit 
was in 2013).

Refer to #10172

-----------------------------------------

Ever since it was removed, GNOME patched a bunch of other stuff and crashes that I'll backport here. Then get the JS stuff working

- [X] Bring back the files
- [X] Backport patches (patch JS files)
- [ ] Work the JS UI
- [ ] Why does the build complain about redefining the POLKIT_I_KNOW_API_IS_SUBJECT_TO_CHANGE?
- [X] Final cleanups (debian packaging, pkexec, etc.)

### CODE REVIEW

**Comment by Fantu** [comment]
@ItzSwirlz thanks for starting do this, even if probably was better wait other comments about the choice (in #10172).
If you want do a fast test you should remove policykit-1-gnome from debian/control of cinnamon and cinnamon-control-center and remove it from the test system.

**Comment by ItzSwirlz** [comment]
And that leaves us with this ugly masterpiece. This is good-it means automatically pkexec uses our authentication agent. Now it's just the UI tuning. I'm pretty new to this stuff, if anyone wants to take a shot at it, go ahead but I'll do what I can to get it to what it was like previously.
Screenshot from 2021-06-25 17-21-58

**Comment by ItzSwirlz** [comment]
Skipped patch https://github.com/GNOME/gnome-shell/commits/master?after=ee1db9ba0a111ccb340bcf3905891684c5731f38+69&branch=master&path%5B%5D=js&path%5B%5D=ui&path%5B%5D=components&path%5B%5D=polkitAgent.js because I couldn't find us having a this.placeSpinner. Not sure how we do on that so I left it.

**Comment by Fantu** [comment]
@ItzSwirlz keep attention to js, don't show warning/error on build but on runtime, years ago when I used on web programming was also more difficult to debug that many other languages that is used.
Also check better when you porting patch from gnome-shell, especially when many years have passed from fork and many things have changed, all the code should always be checked well, even with patches that apply correctly with cherry-pick or minimal manual changes.
In these weeks I have very little time and I can't help you with this task.

**Comment by mtwebster** [comment]
Honestly I'm not sure we're interested in this.

- what will our fallback mode use? I don't want something that's inaccessible in certain situations.
- one reason we got rid of this originally was we felt the less the cinnamon process had to do, the more stable it would be. This is still true.

If we have no choice but to take up gnome-polkit ourselves, so be it. We'll have to consider it.

**Comment by ItzSwirlz** [comment]
> If we have no choice but to take up gnome-polkit ourselves, so be it

Use mate-polkit then, shall I close this?

**Comment by Fantu** [comment]
@mtwebster @ItzSwirlz I think is better continue to discussion about the choice on https://github.com/linuxmint/cinnamon/issues/10172 so also other peoples subscribed can see these message

**Comment by ItzSwirlz** [comment]
We will be going cross-DE

**Pull request closed without merging**
