### PR TITLE
[3.4] Support to drag and drop operation from applications to the desktop

### PR DESCRIPTION
**Pull request by lestcape**
This pull add the ability to drag and drop any cinnamon object to the desktop, where the actor contain a delegate class with an app attribute. So, will support to drag and drop in a general way, elements that contains a GApplication information and create automatically the corresponding .desktop file of the application. Fix: https://github.com/linuxmint/Cinnamon/issues/5028 and partially: https://github.com/linuxmint/Cinnamon/issues/3865

### CODE REVIEW

**Comment by brownsr** [comment]
Appears to need the resulting files to be made executable
screenshot from 2016-12-11 17-23-30
screenshot from 2016-12-11 17-23-52

**Comment by Odyseus** [comment]
Hello, @brownsr.

The .desktop files are made executable by [this line](https://github.com/linuxmint/Cinnamon/pull/6017/files#diff-73d8ed048dbdd9af429eba6537e2660bR74). It's inside a **try {}catch{}** block, so you may find the error in the **glass.log** file perhaps.

**Comment by brownsr** [comment]
Good idea.  The right click option within the menu to add to desktop works fine by comparison, anyway, this is what is in the log:

info t=2016-12-11T19:45:44.691Z FileUtils.changeModeGFile is not a function
trace t=2016-12-11T19:45:44.691Z 
<----------------
NemoDesktopArea.prototype.acceptDrop@/usr/share/cinnamon/js/ui/layout.js:74
_Draggable<._dragActorDropped@/usr/share/cinnamon/js/ui/dnd.js:496
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
_Draggable<._onEvent@/usr/share/cinnamon/js/ui/dnd.js:187
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
_getEventHandlerActor/<@/usr/share/cinnamon/js/ui/dnd.js:56
---------------->

**Comment by Odyseus** [comment]
As I suspected, you may not have a fully updated Cinnamon system. The **changeModeGFile** function was added to **FileUtils** [at the same time that was added to the menu applet](https://github.com/linuxmint/Cinnamon/pull/5972/files#diff-9730f14a54367b06bdc5d0af4a9a5706R145). The updated menu applet also uses **FileUtils.changeModeGFile** to set the permission of the .desktop files copied to the Desktop. Otherwise, you should have received the exact same error when adding from the menu if you were using an up to date Cinnamon.

But this is inconsequential right now. Since this new feature was pushed to be added to Cinnamon 3.4.

**Comment by brownsr** [comment]
I had just spotted this myself.  Will retest.

**Comment by lestcape** [comment]
Well i think this is incomplete anyway, there are not right now a way to support drag and drop between all applications, thats include nemo, for example. This ability need to be implemented from scratch in cinnamon_global.c, and i think it's possible implement this without a problem, but i have dubs abouts what could happen later when Wayland replace the X11 compositor.

Right now, cinnamon use the overlay windows to detect a drag and drop and because of this, we can only received xdnd event inside the clutter actors, but the drag and drop occurs before of that, only we can not detect it. This is an known problem of mutter and muffin. I have a partial solution, if we check the type of the windows, whatever a windows it's create, because when a drag and drop begin the source windows push a new windows with the type DND in X. So, we can check this and detect a drag and drop more faster, and we can have access to the draggable windows that represent the drag and drop.

There are another problem and it's related with how cinnamon_plugings works. When a xdnd event are capture for the atom side the event are not passed to clutter and that inhibit the possibility of use the standard implementation of cinnamon DND to handled xdnd, because we can not received motion event inside clutter in this case.

Finally the are another problem, this is how we can pass the ATOM information of the xdnd to the cinnamon side when we capture the xdnd information. This is a list of atom properties, some of then could have a list of uris or a binary images or whatever the source windows think that it's useful... So only in the client side and with the information about how the specific source works,  we can parse the data in a good way.

But again it's possible do all that and really support a general drag and drop operation, something that it's missing actually.

**Comment by lestcape** [comment]
The necessary code to do all that it's here: https://github.com/swayfreeda/blender-2.77a/tree/5969d704f44952ea8cbecba2ba4150fb4a48e6de/extern/xdnd

Just need to be adapted to the cinnamon work-flow.

**Pull request closed without merging**
