### PR TITLE
Windows overview improvements

### LINKED ISSUE #446: Can't disable animations for expo/scale in Cinnamon Settings
For low spec hardware like netbooks it is very useful that you can turn off window and workspace switching animations within the cinnamon settings.

I think it would be nice to toggle the animations within expo and overview as well because the zooming animation is quite heavy. However this would bring up some things that would need to be discussed first:
1. should the "Enable desktop effects"-switch in the settings be used for expo and overview as well or would it be better to introduce seperate switches?
2. if turning off animations, should expo and overview have no animation at all or should it just be reduced to a simple fade animation?
3. or should the user even be able to select each animation seperately like for the window effects (i.e. for expo enter animation choose between "Zoom" or "Fade") ?

I'm looking forward to hear your opinions on this!

### LINKED ISSUE #7572: expo and overview animation time
This is a feature request. In `expo.js` and `overview.js` the animation time for showing all the workspaces and windows is set by the `ANIMATION_TIME` parameter. The default value for this animation time is set to 0.3 s (expo) and 0.25 s (overview). Currently, unticking the Effects in System Settings does not affect the above animation times. I find that by setting `ANIMATION_TIME` to nearly zero (0.01 s) it makes the displaying of the workspaces and widnow overview through hot corners snappier and appears more responsive. It would be nice if one of the options in the Effects menu was disabling the animation effects for showing all workspaces and windows overview. Thank you. I use Cinnamon 3.8.2 on Arch Linux.

### LINKED ISSUE #7638: Cinnamon ANIMATION_TIME Warning
```
 * Cinnamon 3.8.4
 * Distribution - Mint 19 Tara beta
 * 64 bit
 ```

**Issue**
.xsession-errors logged

(cinnamon:1173): Cjs-WARNING **: 12:20:06.286: Some code accessed the property 'ANIMATION_TIME' on the module 'overview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

(cinnamon:1173): Cjs-WARNING **: 12:20:23.967: Some code accessed the property 'ANIMATION_TIME' on the module 'appSwitcher3D'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

**Steps to reproduce**
Happens using one of Coverflow app switcher, Expo or Scale views (not sure which one)

Cause seems to be in /usr/share/cinnamon/js/ui/overview.js 

// Time for initial animation going into Overview mode
const ANIMATION_TIME = 0.25;

**Expected behaviour**
No Warnings

### LINKED ISSUE #7656: Closing all windows in "Show all windows" should return user to the desktop.
```
 * Cinnamon version (cinnamon 3.8.4)
 * Distribution - (Mint 19)
 * Graphics hardware *and* driver used (NVIDIA Graphics)

**Issue**
Closing all windows using show all windows leaves a blank screen requiring "esc" key to go back to desktop


**Steps to reproduce**
Close all windows using "Show all windows" 


**Expected behaviour**
Unless I'm missing something, once I close all the windows there is nothing else that can be done from this screen. I'm expecting it to close and return me back to the desktop.


**Other information**

thank you for the consideration of this issue. :-)

### LINKED ISSUE #7876: Overview has too much spacing between windows
The spacing between windows in overview mode is much too large.

As a result, windows are ridiculously small. The more windows you open, the worse it gets.

 For reference, gnome-shell has a nicer layout.

### PR DESCRIPTION
**Pull request by germanfr**
* Fix placement of the close button. For some reason, the parent of the window textures can't be a `StWidget` because it doesn't adjust properly to the window bounds.
 * Add hover indicator and fix overlapping windows.
 * Replace Lang.bind with native bind and arrow functions.
 * Use `MetaButtonLayout` to get the side of the close button.
 * Optimize usage of the available space to have larger window previews.
 * Close overview when the last window is closed and show a placeholder if there are no open windows.
 * Go back to desktop on click if there are no open windows.
 * Respect animation effects settings.
 * Remove delay after closing a window.

Depends on linuxmint/muffin#318
Fixes #7876, fixes #7638, fixes #7656, fixes #446, fixes #7572.

### CODE REVIEW

**Comment by germanfr** [comment]
I re-uploaded the last commit fixing some Codacity warnings.

**Comment by germanfr** [comment]
I rebased this to 3.8.9 and squashed and divided some commits into do-one-thing pieces so that this is more understandable in the future.

**Comment by clefebvre** [comment]
@germanfr is this still WIP?

**Comment by germanfr** [comment]
I guess not. I've been using it all this time and had no aparent problems.

**Comment by clefebvre** [comment]
Hi @germanfr ,

A couple of things:

- When I close windows in overview, I get the following error:

```
(cinnamon:7437): Cjs-CRITICAL **: 16:12:18.739: Object St.Bin (0x55f302eff380), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
== Stack trace for context 0x55f2fe8844c0 ==
#0 0x7ffc8b9e6770 b   /usr/share/cinnamon/js/ui/tweener.js:256 (0x7f940bbe3450 @ 37)
#1 0x7ffc8b9e7340 I   resource:///org/cinnamon/cjs/modules/tweener/tweener.js:204 (0x7f940bbdb808 @ 54)
#2 0x7ffc8b9e7490 b   resource:///org/cinnamon/cjs/modules/tweener/tweener.js:338 (0x7f940bbdb890 @ 1742)
#3 0x7ffc8b9e7540 b   resource:///org/cinnamon/cjs/modules/tweener/tweener.js:351 (0x7f940bbdb918 @ 100)
#4 0x7ffc8b9e75d0 b   resource:///org/cinnamon/cjs/modules/tweener/tweener.js:366 (0x7f940bbdb9a0 @ 10)
#5 0x7ffc8b9e76c0 b   resource:///org/cinnamon/cjs/modules/signals.js:142 (0x7f940bbd6918 @ 386)
#6 0x7ffc8b9e7770 b   /usr/share/cinnamon/js/ui/tweener.js:413 (0x7f940bbe3c48 @ 120)
#7 0x7ffc8b9e7820 b   /usr/share/cinnamon/js/ui/tweener.js:389 (0x7f940bbe3bc0 @ 20)
#8 0x7ffc8b9e78f0 b   self-hosted:917 (0x7f940bbe3ef0 @ 394)
```

- When switching focus in overview (either with the mouse or the keyboard arrow keys), there's a slight delay at play (probably due to an animation that wasn't there before). It seemed immediate before, and this feels like a regression.

- The focused window in overview no longer looks focused in themes other than the default one. Could we adapt the PR so that no changes are required in the other themes?

**Comment by germanfr** [comment]
> The focused window in overview no longer looks focused in themes other than the default one. Could we adapt the PR so that no changes are required in the other themes?

Done.


> When switching focus in overview (either with the mouse or the keyboard arrow keys), there's a slight delay at play (probably due to an animation that wasn't there before). It seemed immediate before, and this feels like a regression.

That's actually the small fade in (0.1s the smaller possible unless removed). It feels nicer to my eyes now, it felt clunky with no animation at all. It could be made configurable through "effects" though, like other animations.

> When I close windows in overview, I get the following error:

I'll look at this later, because I can't reproduce right now.

**Comment by jaszhix** [comment]
@germanfr Yeah, so far I only see them when closing windows in the overview.

**Comment by germanfr** [comment]
@clefebvre I think I fixed the warnings issue and some others.
These are the new commits that are not in master:
08993a3 7bbeda4 bb7302f cc5820f 28a9ac9

Should I open a new PR since the previous commits are already in master?

**Comment by clefebvre** [comment]
@germanfr Yes please.

**Pull request closed without merging**
