### PR TITLE
cs_themes: Add a simplified UI

### PR DESCRIPTION
**Pull request by clefebvre**
TODO:

- [x] Don't show styles which point to non-existing themes
- [x] Support a default mode/variant for a given style
- [x] Refresh UI properly
- [x] Harmonize "Themes" vs "Look & Feel" name
- [x] Remove custom legacy/dark sort in custom theme selectors
- [x] Go straight to custom page if the user uses a custom selection
- [x] Remove Custom in combo when it's not needed
- [x] HiDPI support for dots and appearance images

### CODE REVIEW

**Comment by Secret-chest** [comment]
Would you add an API so custom theme devs can use this interface as well?

**Comment by Secret-chest** [comment]
Even though the UI is pretty nice, I think it would be better added in the welcome screen and keep the themes menu as-is.

**Comment by ItzSwirlz** [comment]
Does the color selector only appear if it exists for the theme? Some themes do have multi-color but vary and can only be told depending on the suffix (e.g. Yaru-*)

**Comment by Secret-chest** [comment]
> Does the color selector only appear if it exists for the theme? Some themes do have multi-color but vary and can only be told depending on the suffix (e.g. Yaru-*)

The themes have to be manually added to the dropdown. By default only mint themes and adwaita seem to be available, adwaita seems to only have blue colour.

**Comment by mtwebster** [comment]
Advanced Settings is the old <= 5.4 view - nothing is being taken away. All themes will appear like before, no changes required. For themes to show up in the new page, the definition file would need to include them.

There's only one Adwaita because they only have a light and dark (blue) theme, no other variants.

Mint Welcome is not meant as a normal configuration tool, it's more for initial setup or for less experienced users perform certain major things (like the panel style) without getting lost.

This new theme page is not a novice, introductory tool, it's a less-cluttered way to change the desktop appearance, which is all most users really have a need for.

**Comment by clefebvre** [comment]
> Does the color selector only appear if it exists for the theme? Some themes do have multi-color but vary and can only be told depending on the suffix (e.g. Yaru-*)

We don't look at the theme name to guess available color variants (we'll stop doing that as well in folder-color-switcher btw). We use variant definitions stored in /usr/share/cinnamon/styles.d/.

**Comment by Secret-chest** [comment]
Would it be possible to be able to ship these kinds of definitions when installing a Cinnamon Spices theme?

**Comment by Secret-chest** [comment]
> This new theme page is not a novice, introductory tool, it's a less-cluttered way to change the desktop appearance, which is all most users really have a need for.

I agree, and I think it's got potential since new definition files CAN be shipped with theme debs.

**Comment by clefebvre** [comment]
> Would it be possible to be able to ship these kinds of definitions when installing a Cinnamon Spices theme?

No, it would need write permissions to /usr/share/cinnamon/styles.d/ which is a system directory.

Also, it's not something we'd want. A style is much more than a Spice theme, it's the combination of a GTK theme, an icon theme etc... it's a complete set.

When you're at the point of installing Cinnamon themes, you're already in the Custom tab. If you use a custom set like this the settings app will default to that tab for you whenever you open it again.

**Comment by Secret-chest** [comment]
Looks good then. Serious themes are just going to get installers now (to add them here), aren't they?

**Comment by Secret-chest** [comment]
> Looks good then. Serious themes are just going to get installers now (to add them here), aren't they?

Not sarcasm.

**Comment by clefebvre** [comment]
> Looks good then. Serious themes are just going to get installers now (to add them here), aren't they?

Either that or distributions. The way it works is that they can override each others. Files in /usr/share/cinnamon/styles.d/ are read in alphabetical order. If two files define the same style name, the latter one overwrites the former.

This allows Cinnamon to ship with a predefined style for Adwaita for instance which distributions can override, or which GNOME/Adwaita can override.

**Pull request merged**
