### PR TITLE
[WIP] Improve behavior of thumbnail visibility and animations

### PR DESCRIPTION
**Pull request by mtwebster**
See commit message for details

Should fix: https://github.com/linuxmint/cinnamon/issues/8796

### CODE REVIEW

**Comment by mtwebster** [comment]
issue: If you click on an item in the panel, it temporarily breaks the no-animation sliding for an unknown reason

**Comment by tdeeb** [comment]
Have you had a chance to work on this more @mtwebster? I would really love to see improved thumbnail behavior so they don't disappear as quickly.

**Comment by mtwebster** [comment]
I plan to revisit this soon, just haven't had a chance to.

**Comment by mtwebster** [comment]
Doesn't seem much of an issue anymore, closing

**Pull request closed without merging**
