### PR TITLE
Add Percentage Label to OSD for Volume Control

### PR DESCRIPTION
**Pull request by MysticRyuujin**
Code taken from https://forums.linuxmint.com/viewtopic.php?t=312162

Related to issue #9327

I'm guessing there's a reason this change hasn't been proposed on GitHub yet, but I did a quick search and I didn't see anyone attempt it so :sweat_smile:

It's really @smurphos  code

### CODE REVIEW

**Comment by clefebvre** [comment]
We talked about this before...

.. my TV does that, it shows me a number.. so when it's not loud enough, say I'm at 20....

... I increase the volume until it's perfect (i.e. loud enough but not too much)....

... and then because the number is not round, I decrease it a bit or increase it a bit to fall on something round... 

so if I'm at 24 or 26 I put it at 25... if I'm at 29, I put it at 30...

would you say that number is helping me set my volume? or it's getting in the way?

**Comment by clefebvre** [comment]
I'll argue the opposite also. Say I want to use reduced volume to not annoy people in other rooms, it's not easy for me to assess what volume that might be without going to the other room, but if I did that in the past, I can easily remember a number and know that setting to that number means it won't annoy them. So in this case the value is very helpful.

So with that in mind, I'm OK with adding this.

**Comment by clefebvre** [comment]
From a technical point of view, you can't show "N/A" like that. If the volume is undefined just show nothing (i.e. "").

**Comment by MysticRyuujin** [comment]
It's slightly beyond my skillset but I could see there being a toggle setting in one of the system settings areas for audio/volume control to make it optional for the user.

I like having it there, I suppose others might OCD about it

**Comment by Furvy** [comment]
Is there any chance of this getting better implemented? I opened a bug report on this which does not seem to be acknowledged.

https://github.com/linuxmint/cinnamon/issues/9758

I understand that I should probably try and code this better myself, but I was hoping experts would take a look at it rather than a complete novice like me with no commits attempting such a feat.

**Pull request merged**
