### PR TITLE
cinnamon-settings <spices>: rewrite to simplify code and implement a …

### PR DESCRIPTION
**Pull request by collinss**
…more modern ui

### CODE REVIEW

**Comment by NikoKrause** [comment]
Maybe closes https://github.com/linuxmint/Cinnamon/issues/4833

**Comment by NikoKrause** [comment]
Fixes https://github.com/linuxmint/Cinnamon/issues/3728

**Comment by Odyseus** [comment]
Hello, @collinss.

I have been testing this pull request for various days now. I had a list of issues that I wanted to report, but almost all of them have been fixed in subsequent commits.

- When trying to uninstall an xlet from the **Download <xlets>** tab, the following error is thrown when clicking **Yes** to proceed with the xlet removal.

```shell
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 890, in uninstall
    self.disable_extension(extension_row.uuid, extension_row.name, 0)
AttributeError: 'DownloadSpicesPage' object has no attribute 'disable_extension'
```

I changed that line to the following now it seems to be working as expected.

```python
self.spices.disable_extension(extension_row.uuid)
```

**Comment by Odyseus** [comment]
@collinss.

I found a minor issue with the recently implemented **About** button. The about dialog opened from the xlets manager windows never uses the icon file defined for the xlet (icon.png) because the `metadata` object passed to the `SpicesAboutDialog` prototype doesn't contain a `path` key. So, it always uses the generic `cs-xlet` icon.

I don't think that it is possible to *"fix"* this. I just brought this up to your attention in case your *more experienced eyes* can see a possible solution. LOL

**Comment by collinss** [comment]
@Odyseus nice catch, thanks! That uninstall button was working at one point, I'm not sure what happened. Anyway, I've pushed a fix for it now. As for the missing icon in the about dialog, I did notice it, but I thought it was a general problem with the spices about dialog. I'll see if I can figure something out.

**Comment by collinss** [comment]
@Odyseus the icon issue in the about dialog is now fixed as well.

**Comment by Odyseus** [comment]
@collinss: Tested and working. 👍

**Pull request merged**
