### PR TITLE
Add a setting to warp mouse pointer after Alt+Tab action completes

### PR DESCRIPTION
**Pull request by rcalixte**
* Add a second commit to fix whitespace

### CODE REVIEW

**Comment by mtwebster** [comment]
Works well (though this behavior would drive me nuts).

Not crazy about the setting description though - how about:
```
Warp mouse pointer to the new focused window
```

**Comment by rcalixte** [comment]
> Works well (though this behavior would drive me nuts).

I tested in other modes and I agree. My use case/conditions are:
- Sloppy window focus
- Focus only raises window when clicked
- Alt+Tab focuses and raises window

With this model, I am able to work between multiple windows (across multiple screens and workspaces) without needing the mouse to operate.

Would it make sense to make this setting a dependency of the "Window focus mode" setting? (I ask this being wary of someone somewhere wanting it for an entirely different condition. 😅)




> Not crazy about the setting description though - how about:
> 
> ```
> Warp mouse pointer to the new focused window
> ```

Done.

**Comment by mtwebster** [comment]
Nah it's ok here I think.

Btw, you updated the settings schema summary instead of the string in cs_windows.py (I maybe was too vague, sorry)

**Comment by rcalixte** [comment]
> Btw, you updated the settings schema summary instead of the string in cs_windows.py (I maybe was too vague, sorry)

No need to apologize! Absolutely an oversight on my part. My apologies!

**Pull request merged**
