### PR TITLE
I fixed the "Backup" option in cinnamon center. 

### PR DESCRIPTION
**Pull request by pyroxar**
Now you can open timeshift from the cinnamon center.

### CODE REVIEW

**Comment by collinss** [comment]
Hi @pyroxar some of those external programs are for other distros besides Mint (eg. fedora, arch, etc) You might want to make sure that one isn't being used by any other distro before you remove it.

**Comment by pyroxar** [comment]
If the command is not available to run, cinnamon center doesn't show the icon.

I changed command form "pkexec timeshift-gtk" to "vlc", when i remove vlc, option doesn't still available. 

I tested it with the timeshift too, you can try my code, when you remove the timeshift, option will be removed too.

On the screen I show you the original code which use this "tricks".
image

**Comment by collinss** [comment]
Oh yes, I'm not saying you shouldn't add timeshift, but your pr is also removing `systemd-manager-pkexec` and that may be used by other distros.

**Comment by pyroxar** [comment]
Good point.

**Comment by clefebvre** [comment]
The name should match the name in the application menu, and ideally the window title. Here's it's simply "Timeshift".

Because Timeshift brands itself (i.e. uses a name rather than describing itself as a functionality.. like "System Snapshots" or something..), I'm not sure it should be added to the settings.

I'll close this PR for this reason.

**Pull request closed without merging**
